# Generated by Django 5.2.1 on 2025-06-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(help_text='Campo obrigatório para identificar o treinamento')),
                ('documento', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
            },
        ),
    ]
