# Generated by Django 5.2.1 on 2025-06-14 21:31

import oraculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentos',
            name='tag',
            field=models.TextField(help_text='Campo obrigatório para identificar o treinamento', max_length=20, validators=[oraculo.models.validate_tag]),
        ),
    ]
