# Generated by Django 5.2.1 on 2025-08-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamentos',
            name='treinamento_vetorizado',
            field=models.BooleanField(default=False, help_text='Indica se o treinamento foi vetorizado com sucesso'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='treinamento_finalizado',
            field=models.BooleanField(default=False, help_text='Indica se o treinamento foi finalizado'),
        ),
    ]
