# Generated by Django 5.2.1 on 2025-08-16 19:40

import smart_core_assistant_painel.app.ui.oraculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(help_text='Número de telefone do contato (formato: 5511999999999)', max_length=20, unique=True, validators=[smart_core_assistant_painel.app.ui.oraculo.models.validate_telefone]),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='url_evolution_api',
            field=models.URLField(default='http://www.evolution-api:8080', help_text='URL base da Evolution API'),
        ),
    ]
