# Generated by Django 5.2.5 on 2025-09-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documento',
            name='oraculo_doc_data_cr_f7d25e_idx',
        ),
        migrations.RemoveIndex(
            model_name='documento',
            name='documento_embedding_hnsw_idx',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='avaliacao',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Avaliação do atendimento (1-5)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.AutoField(help_text='Chave primária do registro', primary_key=True, serialize=False),
        ),
    ]
