# Generated by Django 5.2.1 on 2025-08-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraculo", "0002_alter_contato_telefone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="email",
            field=models.EmailField(
                max_length=254,
                blank=True,
                null=True,
                help_text="E-mail do contato",
            ),
        ),
    ]