# Generated by Django 5.2.5 on 2025-09-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0002_remove_documento_oraculo_doc_data_cr_f7d25e_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FluxoConversa',
        ),
    ]
