# Generated by Django 5.2.1 on 2025-06-15 14:56

import oraculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0002_alter_treinamentos_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamentos',
            name='grupo',
            field=models.TextField(default=False, help_text='Campo obrigatório para identificar o grupo do treinamento', max_length=40, validators=[oraculo.models.validate_tag]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treinamentos',
            name='treinamento_finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='tag',
            field=models.TextField(help_text='Campo obrigatório para identificar o treinamento', max_length=40, validators=[oraculo.models.validate_tag]),
        ),
    ]
