# Generated by Django 5.2.5 on 2025-09-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0003_delete_fluxoconversa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='avaliacao',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Avaliação do atendimento (1-5)', null=True),
        ),
    ]
