# Generated by Django 5.2.1 on 2025-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0003_remove_treinamentos_documentos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('data_treinamento', models.ManyToManyField(to='oraculo.datatreinamento')),
            ],
        ),
    ]
