# Generated by Django 5.2.1 on 2025-07-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0004_datatreinamento_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='data_treinamento',
            field=models.ManyToManyField(blank=True, to='oraculo.datatreinamento'),
        ),
    ]
