# Generated by Django 5.2.1 on 2025-07-13 16:02

import django.db.models.deletion
import oraculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0005_alter_pergunta_data_treinamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendenteHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(help_text='Número de WhatsApp do atendente (usado como sessão única)', max_length=20, unique=True, validators=[oraculo.models.validate_telefone])),
                ('nome', models.CharField(help_text='Nome completo do atendente', max_length=100)),
                ('cargo', models.CharField(help_text='Cargo/função do atendente', max_length=100)),
                ('departamento', models.CharField(blank=True, help_text='Departamento ao qual o atendente pertence', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='E-mail corporativo do atendente', max_length=254, null=True)),
                ('telefone_corporativo', models.CharField(blank=True, help_text='Telefone corporativo (opcional)', max_length=20, null=True, validators=[oraculo.models.validate_telefone])),
                ('usuario_sistema', models.CharField(blank=True, help_text='Usuário do sistema para login (se aplicável)', max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Status de atividade do atendente')),
                ('disponivel', models.BooleanField(default=True, help_text='Disponibilidade atual para receber novos atendimentos')),
                ('max_atendimentos_simultaneos', models.PositiveIntegerField(default=5, help_text='Máximo de atendimentos simultâneos permitidos')),
                ('especialidades', models.JSONField(blank=True, default=list, help_text='Lista de especialidades/áreas de conhecimento do atendente')),
                ('horario_trabalho', models.JSONField(blank=True, default=dict, help_text="Horário de trabalho (ex: {'segunda': '08:00-18:00', 'terca': '08:00-18:00'})")),
                ('data_admissao', models.DateField(blank=True, help_text='Data de admissão do atendente na empresa', null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro no sistema')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, help_text='Data da última atividade no sistema')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Informações adicionais do atendente (configurações, preferências, etc.)')),
            ],
            options={
                'verbose_name': 'Atendente Humano',
                'verbose_name_plural': 'Atendentes Humanos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Número de telefone do cliente (formato: +5511999999999)', max_length=20, unique=True, validators=[oraculo.models.validate_telefone])),
                ('nome', models.CharField(blank=True, help_text='Nome do cliente', max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro do cliente')),
                ('ultima_interacao', models.DateTimeField(auto_now=True, help_text='Data da última interação')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Informações adicionais do cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-ultima_interacao'],
            },
        ),
        migrations.CreateModel(
            name='FluxoConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do fluxo de conversa', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do fluxo', null=True)),
                ('condicoes_entrada', models.JSONField(default=dict, help_text='Condições para entrar neste fluxo')),
                ('estados', models.JSONField(default=dict, help_text='Estados e transições do fluxo')),
                ('ativo', models.BooleanField(default=True, help_text='Fluxo ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fluxo de Conversa',
                'verbose_name_plural': 'Fluxos de Conversa',
            },
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='data_treinamento',
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando_inicial', 'Aguardando Interação Inicial'), ('em_andamento', 'Em Andamento'), ('aguardando_cliente', 'Aguardando Cliente'), ('aguardando_atendente', 'Aguardando Atendente'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado'), ('transferido', 'Transferido para Humano')], default='aguardando_inicial', help_text='Status atual do atendimento', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True, help_text='Data de início do atendimento')),
                ('data_fim', models.DateTimeField(blank=True, help_text='Data de finalização do atendimento', null=True)),
                ('assunto', models.CharField(blank=True, help_text='Assunto/resumo do atendimento', max_length=200, null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', help_text='Prioridade do atendimento', max_length=10)),
                ('contexto_conversa', models.JSONField(blank=True, default=dict, help_text='Contexto atual da conversa (variáveis, estado, etc.)')),
                ('historico_status', models.JSONField(blank=True, default=list, help_text='Histórico de mudanças de status')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para categorização do atendimento')),
                ('avaliacao', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Avaliação do atendimento (1-5)', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback do cliente', null=True)),
                ('atendente_humano', models.ForeignKey(blank=True, help_text='Atendente humano responsável pelo atendimento (se transferido)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='oraculo.atendentehumano')),
                ('cliente', models.ForeignKey(help_text='Cliente vinculado ao atendimento', on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='oraculo.cliente')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('documento', 'Documento'), ('localizacao', 'Localização'), ('contato', 'Contato'), ('sistema', 'Mensagem do Sistema')], default='texto', help_text='Tipo da mensagem', max_length=15)),
                ('conteudo', models.TextField(help_text='Conteúdo da mensagem')),
                ('is_from_client', models.BooleanField(default=True, help_text='True se a mensagem é do cliente, False se é do bot/atendente')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp da mensagem')),
                ('message_id_whatsapp', models.CharField(blank=True, help_text='ID da mensagem no WhatsApp', max_length=100, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais da mensagem (mídia, localização, etc.)')),
                ('respondida', models.BooleanField(default=False, help_text='Indica se a mensagem foi respondida')),
                ('resposta_bot', models.TextField(blank=True, help_text='Resposta gerada pelo bot', null=True)),
                ('intent_detectado', models.CharField(blank=True, help_text='Intent detectado pelo processamento de NLP', max_length=100, null=True)),
                ('entidades_extraidas', models.JSONField(blank=True, default=dict, help_text='Entidades extraídas da mensagem')),
                ('atendimento', models.ForeignKey(help_text='Atendimento ao qual a mensagem pertence', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='oraculo.atendimento')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='DataTreinamento',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
    ]
