# Generated by Django 5.2.1 on 2025-07-13 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oraculo", "0006_atendentehumano_cliente_fluxoconversa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atendentehumano",
            name="data_admissao",
        ),
        migrations.RemoveField(
            model_name="atendentehumano",
            name="telefone_corporativo",
        ),
    ]
