# Generated by Django 5.2.1 on 2025-07-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oraculo", "0008_remove_atendentehumano_whatsapp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensagem",
            name="tipo",
            field=models.CharField(
                choices=[
                    (
                        "extendedTextMessage",
                        "Texto com formatação, citações, fontes, etc.",
                    ),
                    ("imageMessage", "Imagem recebida, JPG/PNG, com caption possível"),
                    ("videoMessage", "Vídeo recebido, com legenda possível"),
                    ("audioMessage", "Áudio recebido (.mp4, .mp3), com duração/ptt"),
                    ("documentMessage", "Arquivo genérico (PDF, DOCX etc.)"),
                    ("stickerMessage", "Sticker no formato WebP"),
                    ("locationMessage", "Coordinates de localização (lat/long)"),
                    ("contactMessage", "vCard com dados de contato"),
                    ("listMessage", "Mensagem interativa com opções em lista"),
                    ("buttonsMessage", "Botões clicáveis dentro da mensagem"),
                    ("pollMessage", "Opções de enquete dentro da mensagem"),
                    ("reactMessage", "Reação (emoji) a uma mensagem existente"),
                ],
                default="extendedTextMessage",
                help_text="Tipo da mensagem",
                max_length=25,
            ),
        ),
    ]
