# Generated by Django 5.2.1 on 2025-07-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0010_cliente_ativo'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE oraculo_cliente RENAME TO oraculo_contato;",
            reverse_sql="ALTER TABLE oraculo_contato RENAME TO oraculo_cliente;",
        ),
    ]
