# Generated by Django 5.2.1 on 2025-07-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0013_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='nome_perfil',
            field=models.CharField(blank=True, help_text='Nome do perfil cadastrrado no WhatsApp do contato', max_length=100, null=True),
        ),
    ]
