# Generated by Django 5.2.1 on 2025-07-22 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oraculo", "0014_contato_nome_perfil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contato",
            old_name="nome_perfil",
            new_name="nome_perfil_whatsapp",
        ),
    ]
