# Generated by Django 5.2.1 on 2025-07-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oraculo", "0016_rename_nome_perfil_to_nome_perfil_whatsapp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atendimento",
            old_name="cliente",
            new_name="contato",
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando_inicial", "Aguardando Interação Inicial"),
                    ("em_andamento", "Em Andamento"),
                    ("aguardando_contato", "Aguardando Contato"),
                    ("aguardando_atendente", "Aguardando Atendente"),
                    ("resolvido", "Resolvido"),
                    ("cancelado", "Cancelado"),
                    ("transferido", "Transferido para Humano"),
                ],
                default="aguardando_inicial",
                help_text="Status atual do atendimento",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mensagem",
            name="remetente",
            field=models.CharField(
                choices=[
                    ("contato", "Contato"),
                    ("bot", "Bot/Sistema"),
                    ("atendente_humano", "Atendente Humano"),
                ],
                default="contato",
                help_text="Tipo do remetente da mensagem",
                max_length=20,
            ),
        ),
    ]
