# Generated by Django 5.2.1 on 2025-07-22 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oraculo", "0017_rename_cliente_to_contato"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contato",
            old_name="nome",
            new_name="nome_contato",
        ),
    ]
