# Generated by Django 5.2.5 on 2025-09-10 22:55

import pgvector.django.vector
import smart_core_assistant_painel.app.ui.treinamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCompose',
            fields=[
                ('id', models.AutoField(help_text='Chave primária do registro', primary_key=True, serialize=False)),
                ('tag', models.CharField(help_text="Tag auxiliar para organizar intents (ex: 'orcamento', 'suporte')", max_length=40, validators=[smart_core_assistant_painel.app.ui.treinamento.models.validate_identificador])),
                ('grupo', models.CharField(help_text='Campo obrigatório para identificar o grupo do QueryCompose', max_length=40, validators=[smart_core_assistant_painel.app.ui.treinamento.models.validate_identificador])),
                ('description', models.TextField(help_text='Texto descritivo usado para gerar o embedding (representação do intent)')),
                ('comportamento', models.TextField(help_text='Prompt system que orienta o comportamento da LLM para esse intent')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, help_text='Embedding gerado a partir da description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Query Compose',
                'verbose_name_plural': 'Query Composes',
                'indexes': [models.Index(fields=['tag'], name='treinamento_tag_db3990_idx'), models.Index(fields=['created_at'], name='treinamento_created_022b62_idx')],
            },
        ),
    ]
