# Generated by Django 5.2.5 on 2025-09-10 23:14

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0002_querycompose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querycompose',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='Embedding gerado a partir da description', null=True),
        ),
    ]
