# Generated by Django 5.2.5 on 2025-09-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0003_alter_querycompose_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querycompose',
            old_name='description',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='querycompose',
            name='exemplo',
            field=models.TextField(default='Exemplo não informado', help_text='Exemplo de query que representa o intent'),
            preserve_default=False,
        ),
    ]
