services:
  # Aplicação Django para desenvolvimento
  django-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smart-core-assistant-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DJANGO_DEBUG=True
      - SECRET_KEY_DJANGO=temp-secret-key-for-initial-startup-will-be-replaced-by-firebase-remote-config
      - POSTGRES_DB=smart_core_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_HOST=postgres-django
      - POSTGRES_PORT=5432
      - GOOGLE_APPLICATION_CREDENTIALS=/app/src/smart_core_assistant_painel/modules/initial_loading/utils/keys/firebase_config/firebase_key.json
      # Variáveis dinâmicas serão configuradas pelo start_services
      # SECRET_KEY_DJANGO, OPENAI_API_KEY, GROQ_API_KEY, etc. vêm do Firebase Remote Config
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
      # Persistent data
      - ./src/smart_core_assistant_painel/app/ui/db:/app/src/smart_core_assistant_painel/app/ui/db
      - ./src/smart_core_assistant_painel/app/ui/media:/app/src/smart_core_assistant_painel/app/ui/media
    depends_on:
      - postgres-django
      - evolution-api
    networks:
      - smart-core-network
    # O comando será executado pelo entrypoint script
    # command: ["uv", "run", "python", "src/smart_core_assistant_painel/main.py", "runserver", "0.0.0.0:8000"]

  # Django Q Cluster para desenvolvimento
  django-qcluster:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smart-core-qcluster-dev
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DJANGO_DEBUG=True
      - SECRET_KEY_DJANGO=temp-secret-key-for-initial-startup-will-be-replaced-by-firebase-remote-config
      - POSTGRES_DB=smart_core_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_HOST=postgres-django
      - POSTGRES_PORT=5432
      - GOOGLE_APPLICATION_CREDENTIALS=/app/src/smart_core_assistant_painel/modules/initial_loading/utils/keys/firebase_config/firebase_key.json
      # Variáveis dinâmicas serão configuradas pelo start_services
      # SECRET_KEY_DJANGO, OPENAI_API_KEY, GROQ_API_KEY, etc. vêm do Firebase Remote Config
    volumes:
      - ./src:/app/src
      - ./src/smart_core_assistant_painel/app/ui/db:/app/src/smart_core_assistant_painel/app/ui/db
      - ./src/smart_core_assistant_painel/app/ui/media:/app/src/smart_core_assistant_painel/app/ui/media
    depends_on:
      - django-app
    networks:
      - smart-core-network
    entrypoint: ["/usr/local/bin/docker-entrypoint-qcluster.sh"]
    command: ["uv", "run", "python", "src/smart_core_assistant_painel/app/ui/manage.py", "qcluster"]

  # PostgreSQL para Django
  postgres-django:
    image: postgres:15-alpine
    container_name: postgres-django-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=smart_core_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - postgres_django_data:/var/lib/postgresql/data
    networks:
      - smart-core-network

  # PostgreSQL para Evolution API
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart-core-network

  # Evolution API para desenvolvimento
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution-api-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Configuração conforme documentação oficial v2
      - AUTHENTICATION_API_KEY=evolution-api-key-dev
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution123@postgres:5432/evolution?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_exchange
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - postgres
    networks:
      - smart-core-network



volumes:
  evolution_instances:
    driver: local
  postgres_data:
    driver: local
  postgres_django_data:
    driver: local

networks:
  smart-core-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16