site_name: Smart Core Assistant - Documentation
theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: true
            merge_init_into_class: true
            docstring_style: google

nav:
  - Home: index.md
  - Feature Creation: feature_creation_methodology.md
  - API Reference:
    - AI Engine:
      - 'Feature Facade': api/ai_engine_facade.md
      - 'Análise Conteúdo': api/ai_engine/analise_conteudo.md
      - 'Load Document File': api/ai_engine/load_document_file.md
    - Services:
      - 'Feature Facade': api/services_facade.md
      - 'Vetor Storage': api/services/vetor_storage.md
    - Initial Loading:
      - 'Feature Facade': api/initial_loading_facade.md
      - 'Firebase Init': api/initial_loading/firebase_init.md
