# Generated by Django 5.2.5 on 2025-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='canal',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('web', 'Website')], default='whatsapp', help_text='Canal de origem do atendimento', max_length=20),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data_primeira_resposta',
            field=models.DateTimeField(blank=True, help_text='Data e hora da primeira resposta ao contato', null=True),
        ),
    ]
