# Generated by Django 5.2.7 on 2025-11-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='atendente_humano',
            field=models.ForeignKey(blank=True, help_text='Atendente humano responsável pelo atendimento (se transferido)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='operacional.atendente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='contato',
            field=models.ForeignKey(help_text='Contato vinculado ao atendimento', on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='clientes.contato'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento atual do atendimento (fila Kanban)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='operacional.departamento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='etapa_atual',
            field=models.ForeignKey(blank=True, help_text='Etapa atual do atendimento no fluxo personalizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='operacional.etapafluxo'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='atendimento',
            field=models.ForeignKey(help_text='Atendimento ao qual a mensagem pertence', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='atendimentos.atendimento'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['status', 'departamento'], name='oraculo_ate_status_f1da0a_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['departamento', 'data_ultima_mensagem'], name='oraculo_ate_departa_2bb3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['atendente_humano', 'status'], name='oraculo_ate_atenden_4027c8_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['etapa_atual', 'atendente_humano'], name='oraculo_ate_etapa_a_125143_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['departamento', 'etapa_atual'], name='oraculo_ate_departa_17b2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['valor_orcamento'], name='oraculo_ate_valor_o_232ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['categoria_venda'], name='oraculo_ate_categor_453835_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['tipo_transacao'], name='oraculo_ate_tipo_tr_0a0e44_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['valor_transacao'], name='oraculo_ate_valor_t_b39eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['metodo_pagamento'], name='oraculo_ate_metodo__bc86d0_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['status_financeiro'], name='oraculo_ate_status__9c7118_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['prioridade'], name='oraculo_ate_priorid_775e79_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['tags'], name='oraculo_ate_tags_598b46_idx'),
        ),
    ]
