# Generated by Django 5.2.5 on 2025-09-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('operacional', '0002_atendentehumano_data_ultima_atribuicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_ultima_mensagem',
            field=models.DateTimeField(blank=True, help_text='Data/hora da última mensagem (para ordenação e SLA)', null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento atual do atendimento (fila Kanban)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='operacional.departamento'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['status', 'departamento'], name='oraculo_ate_status_f1da0a_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['departamento', 'data_ultima_mensagem'], name='oraculo_ate_departa_2bb3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['atendente_humano', 'status'], name='oraculo_ate_atenden_4027c8_idx'),
        ),
    ]
