# Generated by Django 5.2.7 on 2025-11-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='atendimento',
            name='oraculo_ate_valor_o_232ff7_idx',
        ),
        migrations.RemoveIndex(
            model_name='atendimento',
            name='oraculo_ate_categor_453835_idx',
        ),
        migrations.RemoveIndex(
            model_name='atendimento',
            name='oraculo_ate_tipo_tr_0a0e44_idx',
        ),
        migrations.RemoveIndex(
            model_name='atendimento',
            name='oraculo_ate_valor_t_b39eaf_idx',
        ),
        migrations.RemoveIndex(
            model_name='atendimento',
            name='oraculo_ate_metodo__bc86d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='atendimento',
            name='oraculo_ate_status__9c7118_idx',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='categoria_venda',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='metodo_pagamento',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='produto_servico',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='status_financeiro',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='tipo_transacao',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='valor_orcamento',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='valor_transacao',
        ),
    ]
