# Generated by Django 5.2.7 on 2025-10-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atendimentos", "0002_enable_pgvector_extension"),
        ("operacional", "0003_remove_atendentehumano_departamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atendimento",
            name="atendente_humano",
            field=models.ForeignKey(
                blank=True,
                help_text="Atendente humano responsável pelo atendimento (se transferido)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atendimentos",
                to="operacional.atendente",
            ),
        ),
    ]
