# Generated by Django 5.2.7 on 2025-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_remove_atendimento_oraculo_ate_valor_o_232ff7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('fila', 'Fila'), ('em_atendimento', 'Em Atendimento'), ('pendencia', 'Pendência'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='fila', help_text='Status atual do atendimento (legado - será substituído por fluxo)', max_length=20),
        ),
    ]
