# Generated by Django 5.2.7 on 2025-11-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_atendimento_fluxo_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('fila', 'Fila'), ('em_atendimento', 'Em Atendimento'), ('pendencia', 'Pendência'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado'), ('transferido', 'Transferido')], default='fila', help_text='Status atual do atendimento (legado - será substituído por fluxo)', max_length=20),
        ),
    ]
