# Generated by Django 5.2.7 on 2025-11-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atendimentos", "0006_alter_atendimento_status"),
        ("clientes", "0003_remove_contato_wa_addressing_mode_and_more"),
        ("operacional", "0009_delete_whatsappinstance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atendimento",
            name="canal",
        ),
        migrations.AddField(
            model_name="atendimento",
            name="bot_pode_atender",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o bot pode responder a este atendimento",
            ),
        ),
        migrations.AddIndex(
            model_name="atendimento",
            index=models.Index(
                fields=["bot_pode_atender"],
                name="oraculo_ate_bot_pod_c83e52_idx",
            ),
        ),
    ]
