# Generated by Django 5.2.7 on 2025-11-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolution_sync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolutioninstance',
            name='server_url',
        ),
    ]
