# Generated by Django 5.2.7 on 2026-02-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        ("evolution_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelist",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whitelist_entries",
                to="clientes.contato",
            ),
        ),
    ]
