# Generated by Django 5.2.7 on 2026-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_sync", "0002_whitelist_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolutioninstance",
            name="connection_state",
            field=models.CharField(
                default="unknown",
                help_text="Estado da conexão: open, close, unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="evolutioninstance",
            name="last_state_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
