# Generated by Django 5.2.7 on 2026-05-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_sync", "0003_evolutioninstance_connection_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolutioninstance",
            name="resposta_bot",
            field=models.BooleanField(
                default=True,
                help_text="Se True, o bot pode responder automaticamente a mensagens desta instância",
            ),
        ),
    ]
