# Generated by Django 5.2.7 on 2026-05-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution_sync', '0006_evolutioninstance_api_version_and_go_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutioninstance',
            name='api_key',
            field=models.CharField(help_text='Token de autenticação da instância (instance token em Go, api_key em v2)', max_length=256),
        ),
        migrations.AlterField(
            model_name='evolutioninstance',
            name='media_storage_backend',
            field=models.CharField(choices=[('none', 'Sem storage (download on-demand)'), ('s3', 'S3 / MinIO no servidor Evolution')], default='s3', help_text="Backend de mídia do servidor Evolution Go. Se 's3', o webhook já traz mediaUrl — sem chamadas extras. Se 'none', o painel chama POST /message/downloadmedia como fallback.", max_length=10),
        ),
    ]
