# Generated by Django 5.2.7 on 2026-05-20 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evolution_sync", "0007_alter_evolutioninstance_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evolutioninstance",
            name="api_version",
        ),
    ]
