# Generated by Django 5.2.7 on 2026-01-03 18:20

import django.db.models.deletion
import smart_core_assistant_painel.app.ui.operacional.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('telefone_instancia', models.CharField(blank=True, help_text='Telefone (instancia Evolution API) deste departamento', max_length=20, null=True, validators=[smart_core_assistant_painel.app.ui.operacional.models.validate_telefone_instancia])),
                ('api_key', models.CharField(blank=True, help_text='Chave de API (Evolution API) deste departamento', max_length=100, null=True, validators=[smart_core_assistant_painel.app.ui.operacional.models.validate_api_key])),
                ('configuracoes', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'oraculo_departamento',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['slug'], name='oraculo_dep_slug_e035bf_idx'), models.Index(fields=['ativo', 'nome'], name='oraculo_dep_ativo_c6d037_idx')],
            },
        ),
        migrations.CreateModel(
            name='FluxoAtendimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome descritivo do fluxo', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descricao detalhada do fluxo de trabalho', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o fluxo esta ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criacao do fluxo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da ultima atualizacao do fluxo')),
                ('departamento', models.ForeignKey(help_text='Departamento ao qual este fluxo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='operacional.departamento')),
            ],
            options={
                'verbose_name': 'Fluxo de Atendimento',
                'verbose_name_plural': 'Fluxos de Atendimento',
                'db_table': 'oraculo_fluxo_atendimento',
                'ordering': ['departamento__nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Nome da etapa (ex: 'Solicitacao de Orcamento')", max_length=50)),
                ('descricao', models.CharField(blank=True, help_text='Descricao opcional da etapa', max_length=200, null=True)),
                ('ordem', models.IntegerField(help_text='Ordem da etapa no fluxo (menor numero primeiro)')),
                ('cor', models.CharField(default='#6B7280', help_text='Cor hexadecimal para identificacao visual (ex: #FF5733)', max_length=7)),
                ('tipo_etapa', models.CharField(choices=[('fila', 'Fila de Entrada'), ('trabalho', 'Em Trabalho'), ('espera', 'Aguardando Resposta'), ('finalizacao', 'Finalizacao')], default='trabalho', help_text='Tipo da etapa para regras de negocio', max_length=20)),
                ('permite_atribuicao', models.BooleanField(default=True, help_text='Indica se atendentes podem ser atribuidos nesta etapa')),
                ('automatico', models.BooleanField(default=False, help_text='Indica se o movimento para esta etapa e automatico')),
                ('regras_transicao', models.JSONField(blank=True, default=dict, help_text='Regras especificas para transicao para esta etapa')),
                ('campos_obrigatorios', models.JSONField(blank=True, default=list, help_text='Lista de campos obrigatorios para entrar nesta etapa')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a etapa esta ativa no fluxo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criacao da etapa')),
                ('fluxo', models.ForeignKey(help_text='Fluxo ao qual esta etapa pertence', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='operacional.fluxoatendimento')),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo',
                'verbose_name_plural': 'Etapas do Fluxo',
                'db_table': 'oraculo_etapa_fluxo',
                'ordering': ['fluxo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.AutoField(help_text='Chave primaria do registro', primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default='', max_length=250, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Numero de telefone do atendente (usado como sessao unica)', max_length=20, null=True, unique=True, validators=[smart_core_assistant_painel.app.ui.operacional.models.validate_telefone])),
                ('nome', models.CharField(help_text='Nome completo do atendente', max_length=100)),
                ('cargo', models.CharField(default='', help_text='Cargo/funcao do atendente', max_length=100)),
                ('email', models.EmailField(help_text='E-mail corporativo do atendente', max_length=254, null=True)),
                ('usuario_sistema', models.CharField(blank=True, help_text='Usuario do sistema para login (se aplicavel)', max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o atendente esta ativo')),
                ('disponivel', models.BooleanField(default=True, help_text='Se o atendente esta aceitando novos atendimentos')),
                ('max_atendimentos_simultaneos', models.PositiveIntegerField(default=5, help_text='Capacidade maxima de atendimentos simultaneos')),
                ('data_ultima_atribuicao', models.DateTimeField(blank=True, help_text='Data e hora da ultima atribuicao de um novo atendimento', null=True)),
                ('horario_trabalho', models.JSONField(blank=True, default=dict, help_text='Horarios de trabalho do atendente')),
                ('especialidades', models.JSONField(blank=True, default=list, help_text='Especialidades do atendente')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Informacoes adicionais do atendente (configuracoes, preferencias, etc.)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro no sistema')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, help_text='Data da ultima atividade no sistema')),
                ('usuario', models.OneToOneField(blank=True, help_text='Usuario do Django associado ao atendente (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendente_humano', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, help_text='Departamento ao qual o atendente pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendentes', to='operacional.departamento')),
                ('fluxo', models.ForeignKey(help_text='Fluxo de atendimento (quadro) ao qual o atendente sera convidado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendentes', to='operacional.fluxoatendimento')),
            ],
            options={
                'verbose_name': 'Atendente',
                'verbose_name_plural': 'Atendentes',
                'db_table': 'oraculo_atendente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=128, unique=True)),
                ('channel', models.CharField(max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('resposta_bot', models.BooleanField(default=True, help_text='Se True, o bot pode responder automaticamente mensagens desta instância')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_instance', to='operacional.atendente')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_instances', to='operacional.departamento')),
            ],
            options={
                'db_table': 'oraculo_app_instance',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key'], name='oraculo_app_api_key_8073df_idx'), models.Index(fields=['channel'], name='oraculo_app_channel_efb030_idx'), models.Index(fields=['departamento'], name='oraculo_app_departa_bcb933_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='etapafluxo',
            index=models.Index(fields=['fluxo', 'ordem'], name='oraculo_eta_fluxo_i_2c1450_idx'),
        ),
        migrations.AddIndex(
            model_name='etapafluxo',
            index=models.Index(fields=['tipo_etapa'], name='oraculo_eta_tipo_et_08009f_idx'),
        ),
        migrations.AddIndex(
            model_name='etapafluxo',
            index=models.Index(fields=['ativo'], name='oraculo_eta_ativo_e02fda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etapafluxo',
            unique_together={('fluxo', 'ordem')},
        ),
        migrations.AddIndex(
            model_name='atendente',
            index=models.Index(fields=['departamento', 'disponivel'], name='oraculo_ate_departa_aa6cea_idx'),
        ),
        migrations.AddIndex(
            model_name='atendente',
            index=models.Index(fields=['disponivel', 'max_atendimentos_simultaneos'], name='oraculo_ate_disponi_390372_idx'),
        ),
        migrations.AddIndex(
            model_name='atendente',
            index=models.Index(fields=['data_ultima_atribuicao'], name='oraculo_ate_data_ul_463ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='atendente',
            index=models.Index(fields=['fluxo'], name='oraculo_ate_fluxo_i_e99ecc_idx'),
        ),
    ]
