# Generated by Django 5.2.5 on 2025-09-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendentehumano',
            name='data_ultima_atribuicao',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última atribuição de um novo atendimento', null=True),
        ),
        migrations.AlterField(
            model_name='atendentehumano',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o atendente está ativo'),
        ),
        migrations.AlterField(
            model_name='atendentehumano',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Se o atendente está aceitando novos atendimentos'),
        ),
        migrations.AlterField(
            model_name='atendentehumano',
            name='especialidades',
            field=models.JSONField(blank=True, default=list, help_text='Especialidades do atendente'),
        ),
        migrations.AlterField(
            model_name='atendentehumano',
            name='horario_trabalho',
            field=models.JSONField(blank=True, default=dict, help_text='Horários de trabalho do atendente'),
        ),
        migrations.AlterField(
            model_name='atendentehumano',
            name='max_atendimentos_simultaneos',
            field=models.PositiveIntegerField(default=5, help_text='Capacidade máxima de atendimentos simultâneos'),
        ),
        migrations.AddIndex(
            model_name='atendentehumano',
            index=models.Index(fields=['departamento', 'disponivel'], name='oraculo_ate_departa_4ca140_idx'),
        ),
        migrations.AddIndex(
            model_name='atendentehumano',
            index=models.Index(fields=['disponivel', 'max_atendimentos_simultaneos'], name='oraculo_ate_disponi_f8a20b_idx'),
        ),
        migrations.AddIndex(
            model_name='atendentehumano',
            index=models.Index(fields=['data_ultima_atribuicao'], name='oraculo_ate_data_ul_d5ca63_idx'),
        ),
    ]
