# Generated by Django 5.2.7 on 2025-11-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operacional", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapafluxo",
            name="ordem",
            field=models.IntegerField(
                help_text=(
                    "Ordem da etapa no fluxo (menor numero primeiro)"
                )
            ),
        ),
    ]