# Generated by Django 5.2.7 on 2025-11-03 00:37

import django.db.models.deletion
import smart_core_assistant_painel.app.ui.operacional.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_atendimento_categoria_venda'),
        ('operacional', '0004_delete_atendentehumano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappinstance',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Instancia WhatsApp', 'verbose_name_plural': 'Instancias WhatsApp'},
        ),
        migrations.AlterField(
            model_name='atendente',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o atendente esta ativo'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='cargo',
            field=models.CharField(help_text='Cargo/funcao do atendente', max_length=100),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='data_ultima_atribuicao',
            field=models.DateTimeField(blank=True, help_text='Data e hora da ultima atribuicao de um novo atendimento', null=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Se o atendente esta aceitando novos atendimentos'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='horario_trabalho',
            field=models.JSONField(blank=True, default=dict, help_text='Horarios de trabalho do atendente'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='id',
            field=models.AutoField(help_text='Chave primaria do registro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='max_atendimentos_simultaneos',
            field=models.PositiveIntegerField(default=5, help_text='Capacidade maxima de atendimentos simultaneos'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Informacoes adicionais do atendente (configuracoes, preferencias, etc.)'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Numero de telefone do atendente (usado como sessao unica)', max_length=20, null=True, unique=True, validators=[smart_core_assistant_painel.app.ui.operacional.models.validate_telefone]),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='ultima_atividade',
            field=models.DateTimeField(auto_now=True, help_text='Data da ultima atividade no sistema'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario do Django associado ao atendente (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendente_humano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='usuario_sistema',
            field=models.CharField(blank=True, help_text='Usuario do sistema para login (se aplicavel)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='api_key',
            field=models.CharField(help_text='Chave de API para autenticacao', max_length=100, unique=True, validators=[smart_core_assistant_painel.app.ui.operacional.models.validate_api_key]),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se a instancia esta ativa'),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criacao do registro'),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento associado a esta instancia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to='operacional.departamento'),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='instance_id',
            field=models.CharField(blank=True, help_text='ID unico da instancia no provedor', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados adicionais da instancia'),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='Atendente dono desta instancia (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_instance', to='operacional.atendente'),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Telefone vinculado a instancia', max_length=20, null=True, unique=True, validators=[smart_core_assistant_painel.app.ui.operacional.models.validate_telefone_instancia]),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='ultima_validacao',
            field=models.DateTimeField(blank=True, help_text='Data da ultima validacao de credenciais', null=True),
        ),
        migrations.CreateModel(
            name='FluxoAtendimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome descritivo do fluxo', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descricao detalhada do fluxo de trabalho', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o fluxo esta ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criacao do fluxo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da ultima atualizacao do fluxo')),
                ('departamento', models.OneToOneField(help_text='Departamento ao qual este fluxo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_atendimento', to='operacional.departamento')),
            ],
            options={
                'verbose_name': 'Fluxo de Atendimento',
                'verbose_name_plural': 'Fluxos de Atendimento',
                'db_table': 'oraculo_fluxo_atendimento',
                'ordering': ['departamento__nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Nome da etapa (ex: 'Solicitacao de Orcamento')", max_length=50)),
                ('descricao', models.CharField(blank=True, help_text='Descricao opcional da etapa', max_length=200, null=True)),
                ('ordem', models.PositiveIntegerField(help_text='Ordem da etapa no fluxo (menor numero primeiro)')),
                ('cor', models.CharField(default='#6B7280', help_text='Cor hexadecimal para identificacao visual (ex: #FF5733)', max_length=7)),
                ('tipo_etapa', models.CharField(choices=[('fila', 'Fila de Entrada'), ('trabalho', 'Em Trabalho'), ('espera', 'Aguardando Resposta'), ('finalizacao', 'Finalizacao')], default='trabalho', help_text='Tipo da etapa para regras de negocio', max_length=20)),
                ('permite_atribuicao', models.BooleanField(default=True, help_text='Indica se atendentes podem ser atribuidos nesta etapa')),
                ('automatico', models.BooleanField(default=False, help_text='Indica se o movimento para esta etapa e automatico')),
                ('regras_transicao', models.JSONField(blank=True, default=dict, help_text='Regras especificas para transicao para esta etapa')),
                ('campos_obrigatorios', models.JSONField(blank=True, default=list, help_text='Lista de campos obrigatorios para entrar nesta etapa')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a etapa esta ativa no fluxo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criacao da etapa')),
                ('fluxo', models.ForeignKey(help_text='Fluxo ao qual esta etapa pertence', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='operacional.fluxoatendimento')),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo',
                'verbose_name_plural': 'Etapas do Fluxo',
                'db_table': 'oraculo_etapa_fluxo',
                'ordering': ['fluxo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoFluxo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, help_text='Motivo da movimentacao (opcional)', null=True)),
                ('dados_complementares', models.JSONField(blank=True, default=dict, help_text='Dados complementares sobre a movimentacao')),
                ('automatico', models.BooleanField(default=False, help_text='Indica se o movimento foi automatico')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, help_text='Data e hora da movimentacao')),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, help_text='Duracao em segundos da etapa anterior (para calculos de SLA)', null=True)),
                ('atendente_destino', models.ForeignKey(blank=True, help_text='Atendente que foi atribuido ao atendimento (se aplicavel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_destino', to='operacional.atendente')),
                ('atendente_origem', models.ForeignKey(blank=True, help_text='Atendente que realizou o movimento (se aplicavel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_origem', to='operacional.atendente')),
                ('atendimento', models.ForeignKey(help_text='Atendimento que foi movido', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_fluxo', to='atendimentos.atendimento')),
                ('etapa_destino', models.ForeignKey(help_text='Etapa para a qual o atendimento foi movido', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_entrada', to='operacional.etapafluxo')),
                ('etapa_origem', models.ForeignKey(blank=True, help_text='Etapa de origem (None para novos atendimentos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_saida', to='operacional.etapafluxo')),
            ],
            options={
                'verbose_name': 'Movimento do Fluxo',
                'verbose_name_plural': 'Movimentos do Fluxo',
                'db_table': 'oraculo_movimento_fluxo',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.AddIndex(
            model_name='etapafluxo',
            index=models.Index(fields=['fluxo', 'ordem'], name='oraculo_eta_fluxo_i_2c1450_idx'),
        ),
        migrations.AddIndex(
            model_name='etapafluxo',
            index=models.Index(fields=['tipo_etapa'], name='oraculo_eta_tipo_et_08009f_idx'),
        ),
        migrations.AddIndex(
            model_name='etapafluxo',
            index=models.Index(fields=['ativo'], name='oraculo_eta_ativo_e02fda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etapafluxo',
            unique_together={('fluxo', 'ordem')},
        ),
        migrations.AddIndex(
            model_name='movimentofluxo',
            index=models.Index(fields=['atendimento', '-data_movimento'], name='oraculo_mov_atendim_adae47_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentofluxo',
            index=models.Index(fields=['etapa_destino', '-data_movimento'], name='oraculo_mov_etapa_d_440de9_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentofluxo',
            index=models.Index(fields=['data_movimento'], name='oraculo_mov_data_mo_7e26c0_idx'),
        ),
    ]
