# Generated by Django 5.2.7 on 2025-11-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0005_alter_whatsappinstance_options_alter_atendente_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoatendimento',
            name='departamento',
            field=models.ForeignKey(help_text='Departamento ao qual este fluxo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='operacional.departamento'),
        ),
    ]
