# Generated by Django 5.2.7 on 2025-11-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_alter_etapafluxo_ordem'),
        ('operacional', '0005_alter_atendente_fluxo_not_null'),
    ]

    operations = [
    ]
