# Generated by Django 5.2.7 on 2025-11-16 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operacional", "0008_appinstance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WhatsAppInstance",
        ),
    ]
