# Generated by Django 5.2.7 on 2025-12-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0009_delete_whatsappinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='email',
            field=models.EmailField(help_text='E-mail corporativo do atendente', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='fluxo',
            field=models.ForeignKey(help_text='Fluxo de atendimento (quadro) ao qual o atendente sera convidado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendentes', to='operacional.fluxoatendimento'),
        ),
    ]
