# Generated by Django 5.2.7 on 2025-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0010_alter_atendente_email_alter_atendente_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='resposta_bot',
            field=models.BooleanField(default=True, help_text='Se True, o bot pode responder automaticamente mensagens desta instância'),
        ),
    ]
