# Generated by Django 5.2.7 on 2026-02-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trello_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trelloboard",
            name="webhook_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
