# Generated by Django 5.2.7 on 2026-01-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("operacional", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atendimento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Chave primária do registro",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fila", "Fila"),
                            ("em_atendimento", "Em Atendimento"),
                            ("pendencia", "Pendência"),
                            ("resolvido", "Resolvido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="fila",
                        help_text="Status atual do atendimento (legado - será substituído por fluxo)",
                        max_length=20,
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data de início do atendimento",
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de finalização do atendimento",
                        null=True,
                    ),
                ),
                (
                    "data_ultima_mensagem",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última mensagem (para ordenação e SLA)",
                        null=True,
                    ),
                ),
                (
                    "assunto",
                    models.CharField(
                        blank=True,
                        help_text="Assunto/resumo do atendimento",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        help_text="Prioridade do atendimento",
                        max_length=10,
                    ),
                ),
                (
                    "contexto_conversa",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contexto atual da conversa (variáveis, estado, etc.)",
                    ),
                ),
                (
                    "historico_status",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Histórico de mudanças de status",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags para categorização do atendimento",
                    ),
                ),
                (
                    "avaliacao",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                        ],
                        help_text="Avaliação do atendimento (1-5)",
                        null=True,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback do contato", null=True
                    ),
                ),
                (
                    "data_primeira_resposta",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da primeira resposta ao contato",
                        null=True,
                    ),
                ),
                (
                    "bot_pode_atender",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o bot pode responder a este atendimento",
                    ),
                ),
                (
                    "atendente_humano",
                    models.ForeignKey(
                        blank=True,
                        help_text="Atendente humano responsável pelo atendimento (se transferido)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos",
                        to="operacional.atendente",
                    ),
                ),
                (
                    "contato",
                    models.ForeignKey(
                        help_text="Contato vinculado ao atendimento",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atendimentos",
                        to="clientes.contato",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Departamento atual do atendimento (fila Kanban)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos",
                        to="operacional.departamento",
                    ),
                ),
                (
                    "etapa_atual",
                    models.ForeignKey(
                        blank=True,
                        help_text="Etapa atual do atendimento no fluxo personalizado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos",
                        to="operacional.etapafluxo",
                    ),
                ),
                (
                    "fluxo_atendimento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fluxo/quadro atual do atendimento (coerente com departamento e etapa_atual)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos",
                        to="operacional.fluxoatendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atendimento",
                "verbose_name_plural": "Atendimentos",
                "db_table": "oraculo_atendimento",
                "ordering": ["-data_inicio"],
                "indexes": [
                    models.Index(
                        fields=["status", "departamento"],
                        name="oraculo_ate_status_f1da0a_idx",
                    ),
                    models.Index(
                        fields=["departamento", "data_ultima_mensagem"],
                        name="oraculo_ate_departa_2bb3f0_idx",
                    ),
                    models.Index(
                        fields=["atendente_humano", "status"],
                        name="oraculo_ate_atenden_4027c8_idx",
                    ),
                    models.Index(
                        fields=["etapa_atual", "atendente_humano"],
                        name="oraculo_ate_etapa_a_125143_idx",
                    ),
                    models.Index(
                        fields=["departamento", "etapa_atual"],
                        name="oraculo_ate_departa_17b2ea_idx",
                    ),
                    models.Index(
                        fields=["fluxo_atendimento"],
                        name="oraculo_ate_fluxo_a_a1f08f_idx",
                    ),
                    models.Index(
                        fields=["prioridade"],
                        name="oraculo_ate_priorid_775e79_idx",
                    ),
                    models.Index(
                        fields=["tags"], name="oraculo_ate_tags_598b46_idx"
                    ),
                    models.Index(
                        fields=["bot_pode_atender"],
                        name="oraculo_ate_bot_pod_c83e52_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Chave primária do registro",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "extendedTextMessage",
                                "Texto com formatação, citações, fontes, etc.",
                            ),
                            (
                                "imageMessage",
                                "Imagem recebida, JPG/PNG, com caption possível",
                            ),
                            (
                                "videoMessage",
                                "Vídeo recebido, com legenda possível",
                            ),
                            (
                                "audioMessage",
                                "Áudio recebido (.mp4, .mp3), com duração/ptt",
                            ),
                            (
                                "documentMessage",
                                "Arquivo genérico (PDF, DOCX etc.)",
                            ),
                            ("stickerMessage", "Sticker no formato WebP"),
                            (
                                "locationMessage",
                                "Coordinates de localização (lat/long)",
                            ),
                            ("contactMessage", "vCard com dados de contato"),
                            (
                                "listMessage",
                                "Mensagem interativa com opções em lista",
                            ),
                            (
                                "buttonsMessage",
                                "Botões clicáveis dentro da mensagem",
                            ),
                            (
                                "pollMessage",
                                "Opções de enquete dentro da mensagem",
                            ),
                            (
                                "reactMessage",
                                "Reação (emoji) a uma mensagem existente",
                            ),
                        ],
                        default="extendedTextMessage",
                        help_text="Tipo da mensagem",
                        max_length=25,
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(help_text="Conteúdo da mensagem"),
                ),
                (
                    "remetente",
                    models.CharField(
                        choices=[
                            ("contato", "Contato"),
                            ("bot", "Bot/Sistema"),
                            ("atendente_humano", "Atendente Humano"),
                        ],
                        default="contato",
                        help_text="Tipo do remetente da mensagem",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp da mensagem"
                    ),
                ),
                (
                    "message_id_whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="ID da mensagem no WhatsApp",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados adicionais da mensagem (mídia, localização, etc.)",
                    ),
                ),
                (
                    "respondida",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a mensagem foi respondida",
                    ),
                ),
                (
                    "resposta_bot",
                    models.TextField(
                        blank=True,
                        help_text="Resposta gerada pelo bot",
                        null=True,
                    ),
                ),
                (
                    "intent_detectado",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Intents detectados pelo processamento de NLP (formato: lista de dicionários como {'saudacao': 'Olá', 'pergunta': 'tudo bem?'})",
                    ),
                ),
                (
                    "entidades_extraidas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Entidades extraídas da mensagem (formato: lista de dicionários como {'pessoa': 'João Silva'})",
                    ),
                ),
                (
                    "confianca_resposta",
                    models.FloatField(
                        blank=True,
                        help_text="Nível de confiança da resposta do bot (0-1)",
                        null=True,
                    ),
                ),
                (
                    "atendimento",
                    models.ForeignKey(
                        help_text="Atendimento ao qual a mensagem pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="atendimentos.atendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "db_table": "oraculo_mensagem",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MovimentoFluxo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "motivo",
                    models.TextField(
                        blank=True,
                        help_text="Motivo da movimentacao (opcional)",
                        null=True,
                    ),
                ),
                (
                    "dados_complementares",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados complementares sobre a movimentacao",
                    ),
                ),
                (
                    "automatico",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o movimento foi automatico",
                    ),
                ),
                (
                    "data_movimento",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora da movimentacao",
                    ),
                ),
                (
                    "duracao_segundos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duracao em segundos da etapa anterior (para calculos de SLA)",
                        null=True,
                    ),
                ),
                (
                    "atendente_destino",
                    models.ForeignKey(
                        blank=True,
                        help_text="Atendente que foi atribuido ao atendimento (se aplicavel)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_destino",
                        to="operacional.atendente",
                    ),
                ),
                (
                    "atendente_origem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Atendente que realizou o movimento (se aplicavel)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_origem",
                        to="operacional.atendente",
                    ),
                ),
                (
                    "atendimento",
                    models.ForeignKey(
                        help_text="Atendimento que foi movido",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos_fluxo",
                        to="atendimentos.atendimento",
                    ),
                ),
                (
                    "etapa_destino",
                    models.ForeignKey(
                        help_text="Etapa para a qual o atendimento foi movido",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos_entrada",
                        to="operacional.etapafluxo",
                    ),
                ),
                (
                    "etapa_origem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Etapa de origem (None para novos atendimentos)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_saida",
                        to="operacional.etapafluxo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento do Fluxo",
                "verbose_name_plural": "Movimentos do Fluxo",
                "db_table": "oraculo_movimento_fluxo",
                "ordering": ["-data_movimento"],
                "indexes": [
                    models.Index(
                        fields=["atendimento", "-data_movimento"],
                        name="oraculo_mov_atendim_adae47_idx",
                    ),
                    models.Index(
                        fields=["etapa_destino", "-data_movimento"],
                        name="oraculo_mov_etapa_d_440de9_idx",
                    ),
                    models.Index(
                        fields=["data_movimento"],
                        name="oraculo_mov_data_mo_7e26c0_idx",
                    ),
                ],
            },
        ),
    ]
