# Generated by Django 5.2.7 on 2026-05-18 12:38

from django.db import migrations, models


def marcar_historico_como_lido(apps, schema_editor):
    """Marca todo o histórico de mensagens existentes como lido.

    Evita que o contador de não-lidas dispare no deploy inicial. Apenas
    mensagens novas (recebidas após esta migration) começam com lido=False.
    """
    Mensagem = apps.get_model("atendimentos", "Mensagem")
    Mensagem.objects.using(schema_editor.connection.alias).update(lido=True)


def reverter_lido(apps, schema_editor):
    """No-op: reverter simplesmente remove o campo (operação inversa do AddField)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_status_arquivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='lido',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se a mensagem (recebida do contato) já foi lida por algum atendente humano via workspace. Não se aplica a mensagens do bot ou do próprio atendente.'),
        ),
        migrations.RunPython(
            marcar_historico_como_lido,
            reverse_code=reverter_lido,
        ),
    ]
