# Generated by Django 5.2.7 on 2026-05-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atendimentos", "0003_mensagem_lido"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="analise_midia",
            field=models.TextField(
                blank=True,
                help_text="Análise gerada pela IA para mídias: transcrição de áudio, resumo de imagem/vídeo, descrição de documento. Separada de 'conteudo'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="arquivo_midia",
            field=models.FileField(
                blank=True,
                help_text="Arquivo binário da mídia decodificada (imagem, áudio, vídeo, documento). Substitui o uso de metadados['base64'] para mídia nova.",
                max_length=255,
                null=True,
                upload_to="midias_atendimento/%Y/%m/",
            ),
        ),
    ]
