# Generated by Django 5.2.7 on 2026-05-23 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atendimentos", "0007_alter_mensagem_quoted_preview"),
        (
            "atendimento_unificado",
            "0005_alter_campopersonalizado_unique_together_and_more",
        ),
    ]

    # Tabelas atu_* já existem (criadas por atendimento_unificado). Aqui apenas
    # movemos o "state" do Django para atendimentos, sem tocar o banco.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Etiqueta",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "nome",
                            models.CharField(
                                help_text="Nome curto da etiqueta (ex: 'Urgente', 'VIP').",
                                max_length=50,
                                unique=True,
                            ),
                        ),
                        (
                            "cor",
                            models.CharField(
                                default="#a98f71",
                                help_text="Cor hexadecimal usada no chip (ex: '#dc2626').",
                                max_length=7,
                            ),
                        ),
                        (
                            "descricao",
                            models.CharField(
                                blank=True,
                                help_text="Descrição exibida no tooltip ao passar o mouse.",
                                max_length=200,
                            ),
                        ),
                        ("ativo", models.BooleanField(default=True)),
                        (
                            "data_criacao",
                            models.DateTimeField(auto_now_add=True),
                        ),
                    ],
                    options={
                        "verbose_name": "Etiqueta",
                        "verbose_name_plural": "Etiquetas",
                        "db_table": "atu_etiqueta",
                        "ordering": ["nome"],
                    },
                ),
                migrations.CreateModel(
                    name="CampoPersonalizado",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "slug",
                            models.SlugField(
                                help_text="Identificador URL-friendly (ex: 'cnpj_cliente').",
                                max_length=64,
                            ),
                        ),
                        ("nome", models.CharField(max_length=120)),
                        (
                            "descricao",
                            models.TextField(
                                blank=True,
                                help_text="Descrição do campo — também usado como hint de extração.",
                            ),
                        ),
                        (
                            "escopo",
                            models.CharField(
                                choices=[
                                    ("GLOBAL", "Global (todos os fluxos)"),
                                    ("FLUXO", "Por Fluxo"),
                                ],
                                default="GLOBAL",
                                max_length=10,
                            ),
                        ),
                        (
                            "fluxo_id",
                            models.BigIntegerField(
                                blank=True,
                                help_text="ID lógico de operacional.FluxoAtendimento (null se GLOBAL).",
                                null=True,
                            ),
                        ),
                        (
                            "tipo",
                            models.CharField(
                                choices=[
                                    ("texto", "Texto"),
                                    ("numero", "Número"),
                                    ("data", "Data"),
                                    ("escolha", "Escolha única"),
                                    ("multipla_escolha", "Múltipla escolha"),
                                    ("booleano", "Booleano"),
                                ],
                                default="texto",
                                max_length=20,
                            ),
                        ),
                        (
                            "opcoes",
                            models.JSONField(
                                blank=True,
                                default=list,
                                help_text="Opções válidas para tipos escolha/multipla_escolha.",
                            ),
                        ),
                        ("obrigatorio", models.BooleanField(default=False)),
                        (
                            "extrair_automaticamente",
                            models.BooleanField(
                                default=True,
                                help_text="Se True, o bot tenta extrair este campo da conversa.",
                            ),
                        ),
                        (
                            "extrair_hint",
                            models.CharField(
                                blank=True,
                                help_text="Dica para a IA sobre como reconhecer este campo.",
                                max_length=500,
                            ),
                        ),
                        (
                            "mostrar_no_card",
                            models.BooleanField(
                                default=True,
                                help_text="Exibir valor como badge no card do Kanban.",
                            ),
                        ),
                        ("ordem", models.PositiveSmallIntegerField(default=0)),
                        ("ativo", models.BooleanField(default=True)),
                        (
                            "data_criacao",
                            models.DateTimeField(auto_now_add=True),
                        ),
                        (
                            "data_atualizacao",
                            models.DateTimeField(auto_now=True),
                        ),
                    ],
                    options={
                        "verbose_name": "Campo Personalizado",
                        "verbose_name_plural": "Campos Personalizados",
                        "db_table": "atu_campo_personalizado",
                        "ordering": ["ordem", "nome"],
                        "indexes": [
                            models.Index(
                                fields=["escopo", "fluxo_id", "ativo"],
                                name="atu_campo_escopo_fluxo_idx",
                            ),
                            models.Index(
                                fields=["extrair_automaticamente", "ativo"],
                                name="atu_campo_extrair_idx",
                            ),
                        ],
                        "unique_together": {("slug", "escopo", "fluxo_id")},
                    },
                ),
                migrations.CreateModel(
                    name="Nota",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "atendimento_id",
                            models.BigIntegerField(
                                db_index=True,
                                help_text="ID lógico de atendimentos.Atendimento.",
                            ),
                        ),
                        (
                            "texto",
                            models.TextField(
                                help_text="Conteúdo livre da nota."
                            ),
                        ),
                        (
                            "criado_por_id",
                            models.BigIntegerField(
                                blank=True,
                                help_text="ID lógico de operacional.Atendente que criou a nota.",
                                null=True,
                            ),
                        ),
                        ("criado_em", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "verbose_name": "Nota",
                        "verbose_name_plural": "Notas",
                        "db_table": "atu_nota",
                        "ordering": ["-criado_em"],
                        "indexes": [
                            models.Index(
                                fields=["atendimento_id", "-criado_em"],
                                name="atu_nota_atend_idx",
                            )
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="EtiquetaAtendimento",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "atendimento_id",
                            models.BigIntegerField(
                                db_index=True,
                                help_text="ID lógico de atendimentos.Atendimento.",
                            ),
                        ),
                        (
                            "aplicada_em",
                            models.DateTimeField(auto_now_add=True),
                        ),
                        (
                            "aplicada_por_id",
                            models.BigIntegerField(
                                blank=True,
                                help_text="ID lógico de operacional.Atendente que aplicou.",
                                null=True,
                            ),
                        ),
                        (
                            "etiqueta",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="aplicacoes",
                                to="atendimentos.etiqueta",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Etiqueta do Atendimento",
                        "verbose_name_plural": "Etiquetas dos Atendimentos",
                        "db_table": "atu_etiqueta_atendimento",
                        "indexes": [
                            models.Index(
                                fields=["atendimento_id"],
                                name="atu_etiq_atend_idx",
                            )
                        ],
                        "unique_together": {("atendimento_id", "etiqueta")},
                    },
                ),
                migrations.CreateModel(
                    name="ValorCampoAtendimento",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "atendimento_id",
                            models.BigIntegerField(
                                help_text="ID lógico de atendimentos.Atendimento (sem FK cruzada)."
                            ),
                        ),
                        (
                            "valor",
                            models.JSONField(
                                help_text="Valor do campo (string, número, lista, bool, etc.)."
                            ),
                        ),
                        (
                            "origem",
                            models.CharField(
                                choices=[
                                    ("MANUAL", "Manual (atendente)"),
                                    ("BOT", "Bot (extração IA)"),
                                    ("IMPORT", "Importado"),
                                ],
                                default="MANUAL",
                                max_length=10,
                            ),
                        ),
                        (
                            "confianca",
                            models.FloatField(
                                blank=True,
                                help_text="Score de confiança da extração (apenas quando origem=BOT).",
                                null=True,
                            ),
                        ),
                        (
                            "mensagem_origem_id",
                            models.BigIntegerField(
                                blank=True,
                                help_text="ID lógico da Mensagem que originou a extração (BOT).",
                                null=True,
                            ),
                        ),
                        (
                            "editado_por_id",
                            models.BigIntegerField(
                                blank=True,
                                help_text="ID lógico do Atendente que editou manualmente.",
                                null=True,
                            ),
                        ),
                        (
                            "data_atualizacao",
                            models.DateTimeField(auto_now=True),
                        ),
                        (
                            "campo",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="valores",
                                to="atendimentos.campopersonalizado",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Valor de Campo",
                        "verbose_name_plural": "Valores de Campos",
                        "db_table": "atu_valor_campo",
                        "indexes": [
                            models.Index(
                                fields=["atendimento_id", "campo"],
                                name="atu_valor_atend_campo_idx",
                            )
                        ],
                        "unique_together": {("atendimento_id", "campo")},
                    },
                ),
            ],
        ),
    ]
