# Generated by Django 5.2.7 on 2026-05-25 15:27

from django.db import migrations, models

import smart_core_assistant_painel.app.atendimentos.models


class Migration(migrations.Migration):
    dependencies = [
        ("atendimentos", "0009_mensagem_resumo_midia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensagem",
            name="arquivo_midia",
            field=models.FileField(
                blank=True,
                help_text="Arquivo binário da mídia decodificada (imagem, áudio, vídeo, documento). Substitui o uso de metadados['base64'] para mídia nova.",
                max_length=255,
                null=True,
                upload_to=smart_core_assistant_painel.app.atendimentos.models.media_upload_to,
            ),
        ),
    ]
