# Generated by Django 5.2.7 on 2026-05-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto_perfil',
            field=models.FileField(blank=True, help_text='Avatar do contato baixado do WhatsApp (profilePictureUrl).', max_length=255, null=True, upload_to='contatos/fotos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contato',
            name='foto_perfil_url_origem',
            field=models.URLField(blank=True, help_text='URL remota usada na última sincronização do avatar; serve como cache-key para evitar redownloads.', max_length=512, null=True),
        ),
    ]
