# Generated by Django 5.2.7 on 2025-10-31 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppFlowyGrid',
            fields=[
                ('grid_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do grid', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do grid', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrição opcional do grid', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do grid')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de atualização do grid')),
            ],
            options={
                'verbose_name': 'Grid AppFlowy',
                'verbose_name_plural': 'Grids AppFlowy',
                'db_table': 'appflowy_grid',
            },
        ),
        migrations.CreateModel(
            name='AppFlowyWorkspace',
            fields=[
                ('workspace_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do workspace', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do workspace', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do workspace')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de atualização do workspace')),
            ],
            options={
                'verbose_name': 'Workspace AppFlowy',
                'verbose_name_plural': 'Workspaces AppFlowy',
                'db_table': 'appflowy_workspace',
            },
        ),
        migrations.CreateModel(
            name='AppFlowyColumn',
            fields=[
                ('column_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da coluna', primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Chave/slug da coluna (ex.: 'status', 'priority')", max_length=50)),
                ('name', models.CharField(help_text='Nome exibido da coluna', max_length=100)),
                ('type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('boolean', 'Boolean')], help_text='Tipo da coluna', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('required', models.BooleanField(default=False, help_text='Indica se a coluna é obrigatória')),
                ('grid', models.ForeignKey(help_text='Grid ao qual a coluna pertence', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='appflowy_adapter.appflowygrid')),
            ],
            options={
                'verbose_name': 'Coluna AppFlowy',
                'verbose_name_plural': 'Colunas AppFlowy',
                'db_table': 'appflowy_column',
                'ordering': ['order', 'name'],
                'unique_together': {('grid', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AppFlowyRow',
            fields=[
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da linha', primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(db_index=True, help_text='Chave idempotente associada ao domínio (ex.: Atendimento)', max_length=120)),
                ('received_at', models.DateTimeField(blank=True, help_text='Data/hora de recebimento inicial', null=True)),
                ('name', models.CharField(help_text='Nome/título do item', max_length=200)),
                ('channel', models.CharField(help_text='Canal de origem (ex.: whatsapp)', max_length=50)),
                ('status', models.CharField(help_text='Status normalizado', max_length=50)),
                ('priority', models.CharField(help_text='Prioridade normalizada', max_length=20)),
                ('assigned_to', models.CharField(blank=True, default='', help_text='Responsável pelo item', max_length=120)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags do item')),
                ('last_message', models.TextField(blank=True, default='', help_text='Última mensagem relevante (se aplicável)')),
                ('sla_due', models.DateTimeField(blank=True, help_text='Data/hora de SLA (se aplicável)', null=True)),
                ('version', models.IntegerField(default=1, help_text='Versão incrementada a cada atualização')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de atualização da linha')),
                ('grid', models.ForeignKey(help_text='Grid ao qual a linha pertence', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='appflowy_adapter.appflowygrid')),
            ],
            options={
                'verbose_name': 'Linha AppFlowy',
                'verbose_name_plural': 'Linhas AppFlowy',
                'db_table': 'appflowy_row',
            },
        ),
        migrations.CreateModel(
            name='AppFlowyRowValue',
            fields=[
                ('value_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do valor', primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict, help_text='Valor armazenado em JSON')),
                ('column', models.ForeignKey(help_text='Coluna à qual o valor pertence', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='appflowy_adapter.appflowycolumn')),
                ('row', models.ForeignKey(help_text='Linha à qual o valor pertence', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='appflowy_adapter.appflowyrow')),
            ],
            options={
                'verbose_name': 'Valor de Coluna AppFlowy',
                'verbose_name_plural': 'Valores de Coluna AppFlowy',
                'db_table': 'appflowy_row_value',
            },
        ),
        migrations.CreateModel(
            name='AppFlowySyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp do último delta consumido')),
                ('grid', models.OneToOneField(help_text='Grid associado ao estado de sincronização', on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='appflowy_adapter.appflowygrid')),
            ],
            options={
                'verbose_name': 'Estado de Sincronização',
                'verbose_name_plural': 'Estados de Sincronização',
                'db_table': 'appflowy_sync_state',
            },
        ),
        migrations.AddField(
            model_name='appflowygrid',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace ao qual o grid pertence', on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='appflowy_adapter.appflowyworkspace'),
        ),
        migrations.AddIndex(
            model_name='appflowyrow',
            index=models.Index(fields=['grid', 'ticket_id'], name='appflowy_ro_grid_id_eb4398_idx'),
        ),
        migrations.AddIndex(
            model_name='appflowyrow',
            index=models.Index(fields=['grid', 'updated_at'], name='appflowy_ro_grid_id_fe3455_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appflowyrowvalue',
            unique_together={('row', 'column')},
        ),
    ]
