# Generated by Django 5.2.7 on 2026-02-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treinamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryTestFeedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mensagem_original",
                    models.TextField(
                        help_text="Mensagem enviada pelo usuário no teste"
                    ),
                ),
                (
                    "resposta_bot",
                    models.TextField(help_text="Resposta gerada pelo bot"),
                ),
                (
                    "resposta_corrigida",
                    models.TextField(
                        blank=True,
                        help_text="Resposta corrigida pelo usuário (se avaliação ruim)",
                        null=True,
                    ),
                ),
                (
                    "avaliacao",
                    models.CharField(
                        help_text="Avaliação: 'bom' ou 'ruim'", max_length=10
                    ),
                ),
                (
                    "confiabilidade",
                    models.FloatField(
                        default=0.0,
                        help_text="Score de confiabilidade (0.0 a 1.0)",
                    ),
                ),
                (
                    "entidades_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Entidades extraídas da mensagem",
                    ),
                ),
                (
                    "intents_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Intents detectados na mensagem",
                    ),
                ),
                (
                    "documentos_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs dos documentos RAG utilizados",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feedback de Teste",
                "verbose_name_plural": "Feedbacks de Teste",
                "db_table": "treinamento_query_test_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
