# Generated by Django 5.2.7 on 2026-01-03 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_instances', models.IntegerField(default=1, help_text='Máximo de instâncias Evolution. -1 para ilimitado')),
                ('max_departments', models.IntegerField(default=1, help_text='Máximo de departamentos. -1 para ilimitado')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('setup_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('payment_gateway', models.CharField(blank=True, help_text='Ex: asaas, stripe', max_length=50)),
                ('external_customer_id', models.CharField(blank=True, max_length=100)),
                ('external_subscription_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('TRANSFER', 'Transferência'), ('CASH', 'Dinheiro'), ('BOLETO', 'Boleto'), ('OTHER', 'Outro')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_empresa', models.TextField(blank=True, default='', help_text='Descreva sua empresa: nome, localização, produtos, serviços, missão, visão e valores. Essas informações serão usadas pelo bot para responder perguntas sobre a empresa.', verbose_name='Dados da Empresa')),
                ('persona_bot', models.TextField(blank=True, default='', help_text="Defina a identidade do bot: nome, tom de voz, estilo de comunicação e como ele deve se apresentar aos clientes. Ex: 'Você é o Smart, assistente da Gráfica Ecoprint...'", verbose_name='Persona do Bot')),
                ('msg_fallback', models.CharField(blank=True, default='Recebemos sua mensagem. Em breve retornaremos.', help_text='Mensagem enviada quando o bot não consegue processar a mensagem do cliente.', max_length=500, verbose_name='Mensagem Fallback')),
                ('msg_sem_info', models.CharField(blank=True, default='Desculpe, não encontrei informações sobre isso.', help_text='Mensagem enviada quando não há dados no treinamento para responder a pergunta do cliente.', max_length=500, verbose_name='Mensagem Sem Informação')),
                ('msg_transferencia', models.CharField(blank=True, default='Vou transferir seu atendimento para o setor responsável.', help_text='Mensagem enviada ao cliente quando o atendimento é transferido para um atendente humano.', max_length=500, verbose_name='Mensagem de Transferência')),
                ('entity_types', models.JSONField(blank=True, default=dict, help_text='JSON com os tipos de entidade que o bot deve extrair das mensagens. Cada categoria define campos e descrições. Ex: produtos_servicos, dados_financeiros, etc.', verbose_name='Tipos de Entidade')),
                ('llm_class', models.CharField(blank=True, default='', help_text='Classe do LLM a usar: ChatGroq, ChatOpenAI, ChatOllama. Se vazio, usa a configuração global.', max_length=50, verbose_name='Classe LLM')),
                ('model', models.CharField(blank=True, default='', help_text='Modelo específico a usar, ex: llama-3.1-70b-versatile, gpt-4o, openai/gpt-4o-mini. Se vazio, usa a configuração global.', max_length=100, verbose_name='Modelo LLM')),
                ('api_keys', models.JSONField(blank=True, default=dict, help_text='API Keys específicas do tenant. Chaves válidas: groq_api_key, openai_api_key, huggingface_api_key. Se preenchido, sobrescreve as API Keys globais.', verbose_name='API Keys do Tenant')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('_password', models.CharField(db_column='password', max_length=500)),
                ('ssl_mode', models.CharField(default='disable', max_length=50)),
                ('connection_valid', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('schema_version', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField()),
                ('_api_key', models.CharField(db_column='api_key', max_length=500)),
                ('instance_name', models.CharField(default='atendimento', max_length=100)),
                ('connection_valid', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('staff', 'Funcionário'), ('viewer', 'Visualizador')], default='staff', max_length=20)),
                ('module_permissions', models.JSONField(blank=True, default=dict)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Convite de Tenant',
                'verbose_name_plural': 'Convites de Tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_api_key', models.CharField(db_column='api_key', max_length=500)),
                ('_api_secret', models.CharField(db_column='api_secret', max_length=500)),
                ('_token', models.CharField(db_column='token', max_length=500)),
                ('workspace_id', models.CharField(max_length=100)),
                ('webhook_id', models.CharField(blank=True, max_length=100)),
                ('webhook_callback_url', models.URLField(blank=True)),
                ('connection_valid', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trello_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('staff', 'Funcionário'), ('viewer', 'Visualizador')], default='staff', max_length=20)),
                ('module_permissions', models.JSONField(blank=True, default=dict, help_text='{modulo: {view: bool, edit: bool, delete: bool}}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenant_users', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário do Tenant',
                'verbose_name_plural': 'Funcionários do Tenant',
            },
        ),
    ]
