# Generated by Django 5.2.7 on 2026-02-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenants",
            "0002_tenant_onboarding_step_tenantconfig_brand_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="access_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
