# Generated by Django 5.2.7 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_tenant_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="bot_agent_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Nome exibido no WhatsApp antes das mensagens do bot. "
                    "Ex: *Íris:* Olá, como posso ajudar hoje?"
                ),
                max_length=80,
                verbose_name="Nome do Agente do Bot",
            ),
        ),
    ]
