# Generated by Django 5.2.7 on 2026-02-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantconfig_bot_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='transcription_model',
            field=models.CharField(blank=True, default='', help_text='Modelo de transcrição (ex: whisper-1). Se vazio, usa a configuração global.', max_length=100, verbose_name='Modelo de Transcrição'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='transcription_provider',
            field=models.CharField(blank=True, default='', help_text='Provedor de transcrição (openai, groq). Se vazio, usa a configuração global.', max_length=50, verbose_name='Provedor de Transcrição'),
        ),
    ]
