# Generated by Django 5.2.7 on 2025-11-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_fluxo_id', models.BigIntegerField()),
                ('list_external_id', models.CharField(max_length=128)),
                ('status_name', models.CharField(max_length=128)),
                ('status_type', models.CharField(max_length=16)),
                ('color', models.CharField(max_length=16)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ClickUp Status',
                'verbose_name_plural': 'ClickUp Statuses',
                'constraints': [models.UniqueConstraint(fields=('etapa_fluxo_id', 'list_external_id'), name='uniq_etapa_list_status')],
            },
        ),
    ]
