# Generated by Django 5.2.7 on 2025-11-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_sync', '0003_clickupfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickupfolder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
