# Generated by Django 5.2.7 on 2025-11-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clickup_sync", "0004_alter_clickupfolder_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickupCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("field_id", models.CharField(max_length=128, unique=True)),
                ("type", models.CharField(max_length=32)),
                ("scope_type", models.CharField(max_length=16)),
                ("scope_external_id", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ClickUp Custom Field",
                "verbose_name_plural": "ClickUp Custom Fields",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_external_id", "name"),
                        name="uniq_scope_name_custom_field",
                    )
                ],
            },
        ),
    ]
