# Generated by Codex on 2026-02-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operacional", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atendente",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atendente_humano",
                to=settings.AUTH_USER_MODEL,
                db_constraint=False,
                help_text="Usuario do Django associado ao atendente (opcional)",
            ),
        ),
    ]

