# Generated by Django 5.2.5 on 2025-10-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfig',
            fields=[
                ('id', models.AutoField(help_text='Chave primária do registro', primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Chave única da configuração (ex: 'notion_token')", max_length=100, unique=True)),
                ('value', models.JSONField(help_text='Valor da configuração (pode ser string, dict, list, etc)')),
                ('description', models.TextField(blank=True, help_text='Descrição do propósito desta configuração', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se a configuração está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da configuração')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Sincronização',
                'verbose_name_plural': 'Configurações de Sincronização',
                'db_table': 'notion_sync_config',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ClienteSync',
            fields=[
                ('id', models.AutoField(help_text='Chave primária do registro', primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, help_text='ID do registro na plataforma externa (ex: page_id Notion)', max_length=255, null=True, unique=True)),
                ('is_synced', models.BooleanField(default=False, help_text='Se o registro está atualmente sincronizado')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp da última sincronização bem-sucedida', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Última mensagem de erro de sincronização', null=True)),
                ('sync_attempts', models.IntegerField(default=0, help_text='Número total de tentativas de sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do tracking')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização do tracking')),
                ('cliente', models.OneToOneField(help_text='Cliente original sendo sincronizado', on_delete=django.db.models.deletion.CASCADE, related_name='sync_metadata', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Sincronização de Cliente',
                'verbose_name_plural': 'Sincronizações de Clientes',
                'db_table': 'notion_sync_cliente',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContatoSync',
            fields=[
                ('id', models.AutoField(help_text='Chave primária do registro', primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, help_text='ID do registro na plataforma externa (ex: page_id Notion)', max_length=255, null=True, unique=True)),
                ('is_synced', models.BooleanField(default=False, help_text='Se o registro está atualmente sincronizado')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp da última sincronização bem-sucedida', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Última mensagem de erro de sincronização', null=True)),
                ('sync_attempts', models.IntegerField(default=0, help_text='Número total de tentativas de sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do tracking')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização do tracking')),
                ('contato', models.OneToOneField(help_text='Contato original sendo sincronizado', on_delete=django.db.models.deletion.CASCADE, related_name='sync_metadata', to='clientes.contato')),
            ],
            options={
                'verbose_name': 'Sincronização de Contato',
                'verbose_name_plural': 'Sincronizações de Contatos',
                'db_table': 'notion_sync_contato',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(help_text='Chave primária do registro', primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="Nome do modelo Django (ex: 'Cliente', 'Contato')", max_length=100)),
                ('django_id', models.IntegerField(blank=True, help_text='ID do registro no Django', null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID do registro na plataforma externa', max_length=255, null=True)),
                ('operation', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Deletar'), ('sync', 'Sincronizar')], help_text='Tipo de operação realizada', max_length=20)),
                ('direction', models.CharField(choices=[('django_to_external', 'Django → Externa'), ('external_to_django', 'Externa → Django'), ('bidirectional', 'Bidirecional')], help_text='Direção da sincronização', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('error', 'Erro'), ('retry', 'Tentando Novamente')], default='pending', help_text='Status da operação', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro se operação falhou', null=True)),
                ('error_details', models.JSONField(blank=True, help_text='Detalhes adicionais do erro (stack trace, etc)', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duração da operação em milissegundos', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Número de tentativas de retry')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp da operação')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'db_table': 'notion_sync_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'django_id'], name='idx_sync_log_model'), models.Index(fields=['status', 'created_at'], name='idx_sync_log_status')],
            },
        ),
    ]
