# Generated by Django on 2025-10-23 23:11 via generate_migration_only.py

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Import pgvector with fallback
try:
    import pgvector.django
except ImportError:
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Extensão pgvector - criar apenas se estiver disponível
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),

        # SyncConfig
        migrations.CreateModel(
            name='SyncConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Chave única da configuração', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Valor da configuração')),
                ('description', models.TextField(blank=True, help_text='Descrição da configuração')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Sincronização',
                'verbose_name_plural': 'Configurações de Sincronização',
                'ordering': ['key'],
                'db_table': 'notion_sync_config',
            },
        ),

        # NotionDatabaseConfig
        migrations.CreateModel(
            name='NotionDatabaseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único para referência no código', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nome descritivo da database/página no Notion', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do uso desta configuração')),
                ('notion_database_id', models.UUIDField(help_text='ID da database no Notion (formato UUID)')),
                ('data_source_id', models.UUIDField(blank=True, help_text='ID do data source (API v2025-09-03)', null=True)),
                ('notion_page_id', models.UUIDField(blank=True, help_text='ID da página principal (opcional, para hierarquias)', null=True)),
                ('django_model', models.CharField(help_text='Modelo Django correspondente (app.Model)', max_length=100)),
                ('django_app_label', models.CharField(help_text='App Django onde o modelo está definido', max_length=50)),
                ('notion_schema', models.JSONField(default=dict, help_text='Schema completo das propriedades do Notion')),
                ('field_mappings', models.JSONField(default=dict, help_text='Mapeamento campo_django → campo_notion')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Habilita/desabilita sincronização')),
                ('sync_direction', models.CharField(choices=[('bidirectional', 'Bidirecional'), ('django_to_notion', 'Django → Notion'), ('notion_to_django', 'Notion → Django')], default='bidirectional', help_text='Direção da sincronização', max_length=20)),
                ('sync_priority', models.IntegerField(choices=[(1, 'Baixa'), (3, 'Média'), (5, 'Normal'), (7, 'Alta'), (10, 'Crítica')], default=5, help_text='Prioridade na fila de sincronização')),
                ('auto_sync', models.BooleanField(default=True, help_text='Sincroniza automaticamente após alterações')),
                ('batch_sync_enabled', models.BooleanField(default=False, help_text='Permite sincronização em lote')),
                ('batch_size', models.IntegerField(default=50, help_text='Tamanho do lote para sincronização em batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais e configurações customizadas')),
            ],
            options={
                'verbose_name': 'Configuração Notion',
                'verbose_name_plural': 'Configurações Notion',
                'ordering': ['sync_priority', 'slug'],
                'db_table': 'notion_database_config',
                'indexes': [
                    models.Index(fields=['slug'], name='notion_db_slug_idx'),
                    models.Index(fields=['django_model'], name='notion_db_model_idx'),
                    models.Index(fields=['sync_enabled'], name='notion_db_sync_enabled_idx'),
                    models.Index(fields=['sync_priority'], name='notion_db_priority_idx'),
                ],
            },
        ),

        # NotionObjectMapping
        migrations.CreateModel(
            name='NotionObjectMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_model', models.CharField(help_text='Modelo Django (app.Model)', max_length=100)),
                ('local_id', models.IntegerField(help_text='ID do registro local')),
                ('external_id', models.CharField(db_index=True, help_text='ID da página no Notion', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_mappings', to='notion_sync.notiondatabaseconfig')),
            ],
            options={
                'verbose_name': 'Mapeamento Notion',
                'verbose_name_plural': 'Mapeamentos Notion',
                'db_table': 'notion_object_mapping',
                'indexes': [
                    models.Index(fields=['external_id'], name='notion_map_external_idx'),
                    models.Index(fields=['local_model', 'local_id'], name='notion_map_local_idx'),
                    models.Index(fields=['config'], name='notion_map_config_idx'),
                ],
                'unique_together': {('local_model', 'local_id')},
            },
        ),

        # SyncLog
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('sync', 'Sincronização')], help_text='Tipo da operação', max_length=20)),
                ('model_name', models.CharField(help_text='Modelo Django (app.Model)', max_length=100)),
                ('object_id', models.IntegerField(help_text='ID do objeto local')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID do objeto no Notion', max_length=36, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('success', 'Sucesso'), ('error', 'Erro'), ('cancelled', 'Cancelado')], default='pending', help_text='Status da operação', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Mensagem descritiva')),
                ('error_details', models.JSONField(blank=True, help_text='Detalhes do erro (JSON)', null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Dados enviados na requisição', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Dados recebidos na resposta', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Início da operação', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Término da operação', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duração em milissegundos', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='notion_sync.notiondatabaseconfig')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-created_at'],
                'db_table': 'notion_sync_log',
                'indexes': [
                    models.Index(fields=['model_name', 'object_id'], name='notion_log_model_obj_idx'),
                    models.Index(fields=['status'], name='notion_log_status_idx'),
                    models.Index(fields=['external_id'], name='notion_log_external_idx'),
                    models.Index(fields=['started_at'], name='notion_log_started_idx'),
                    models.Index(fields=['model_name', 'status'], name='notion_log_model_status_idx'),
                ],
            },
        ),

        # ContatoSync
        migrations.CreateModel(
            name='ContatoSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID da página correspondente no Notion (UUID sem dashes)', max_length=36, null=True, unique=True)),
                ('nome_formatado', models.CharField(help_text='Nome já formatado e validado para o Notion', max_length=200)),
                ('email_normalizado', models.EmailField(blank=True, help_text='Email validado e normalizado', max_length=254, null=True)),
                ('telefone_formatado', models.CharField(blank=True, help_text='Telefone no formato internacional (+55XX999999999)', max_length=20, null=True)),
                ('principal', models.BooleanField(default=False, help_text='É contato principal do cliente?')),
                ('tags_formatadas', models.JSONField(blank=True, default=list, help_text='Tags formatadas para select/multi-select do Notion')),
                ('notion_properties', models.JSONField(default=dict, help_text='Propriedades completas formatadas para API Notion')),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('error', 'Erro'), ('disabled', 'Desabilitado')], default='pending', help_text='Status atual da sincronização', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Data/hora da última sincronização', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Detalhes do último erro de sincronização', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Número de tentativas de sincronização')),
                ('sync_metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais sobre a sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contato_syncs', to='notion_sync.notiondatabaseconfig')),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='clientes.Contato')),
            ],
            options={
                'verbose_name': 'Contato Sync',
                'verbose_name_plural': 'Contatos Sync',
                'ordering': ['contato__nome_contato'],
                'db_table': 'notion_sync_contato',
                'indexes': [
                    models.Index(fields=['external_id'], name='notion_contato_external_idx'),
                    models.Index(fields=['sync_status'], name='notion_contato_status_idx'),
                    models.Index(fields=['contato'], name='notion_contato_contato_idx'),
                    models.Index(fields=['last_sync_at'], name='notion_contato_last_sync_idx'),
                    models.Index(fields=['sync_status', 'config'], name='notion_contato_status_config_idx'),
                ],
            },
        ),

        # ClienteSync
        migrations.CreateModel(
            name='ClienteSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID da página correspondente no Notion', max_length=36, null=True, unique=True)),
                ('nome_fantasia_formatado', models.CharField(help_text='Nome fantasia formatado', max_length=200)),
                ('razao_social_formatada', models.CharField(blank=True, help_text='Razão social formatada', max_length=200, null=True)),
                ('cnpj_formatado', models.CharField(blank=True, help_text='CNPJ formatado (apenas dígitos)', max_length=18, null=True)),
                ('telefone_formatado', models.CharField(blank=True, help_text='Telefone formatado', max_length=20, null=True)),
                ('endereco_completo', models.TextField(blank=True, help_text='Endereço completo formatado', null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('error', 'Erro'), ('disabled', 'Desabilitado')], default='pending', help_text='Status atual da sincronização', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Data/hora da última sincronização', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Detalhes do último erro de sincronização', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Número de tentativas de sincronização')),
                ('notion_properties', models.JSONField(default=dict, help_text='Propriedades completas formatadas para API Notion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_syncs', to='notion_sync.notiondatabaseconfig')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Cliente Sync',
                'verbose_name_plural': 'Clientes Sync',
                'ordering': ['cliente__nome_fantasia'],
                'db_table': 'notion_sync_cliente',
                'indexes': [
                    models.Index(fields=['external_id'], name='notion_cliente_external_idx'),
                    models.Index(fields=['sync_status'], name='notion_cliente_status_idx'),
                    models.Index(fields=['cliente'], name='notion_cliente_cliente_idx'),
                    models.Index(fields=['last_sync_at'], name='notion_cliente_last_sync_idx'),
                ],
            },
        ),

        # DepartamentoSync
        migrations.CreateModel(
            name='DepartamentoSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID da página correspondente no Notion', max_length=36, null=True, unique=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('error', 'Erro')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_syncs', to='notion_sync.notiondatabaseconfig')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='operacional.Departamento')),
            ],
            options={
                'verbose_name': 'Departamento Sync',
                'verbose_name_plural': 'Departamentos Sync',
                'db_table': 'notion_sync_departamento',
                'indexes': [
                    models.Index(fields=['external_id'], name='notion_depto_external_idx'),
                    models.Index(fields=['sync_status'], name='notion_depto_status_idx'),
                ],
            },
        ),

        # AtendenteSync
        migrations.CreateModel(
            name='AtendenteSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID da página correspondente no Notion', max_length=36, null=True, unique=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('error', 'Erro')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendente_syncs', to='notion_sync.notiondatabaseconfig')),
                ('atendente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='operacional.AtendenteHumano')),
            ],
            options={
                'verbose_name': 'Atendente Sync',
                'verbose_name_plural': 'Atendentes Sync',
                'db_table': 'notion_sync_atendente',
                'indexes': [
                    models.Index(fields=['external_id'], name='notion_atend_external_idx'),
                    models.Index(fields=['sync_status'], name='notion_atend_status_idx'),
                ],
            },
        ),

        # MensagemSync
        migrations.CreateModel(
            name='MensagemSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID da página correspondente no Notion', max_length=36, null=True, unique=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('error', 'Erro')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_syncs', to='notion_sync.notiondatabaseconfig')),
                ('mensagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='atendimentos.Mensagem')),
            ],
            options={
                'verbose_name': 'Mensagem Sync',
                'verbose_name_plural': 'Mensagens Sync',
                'db_table': 'notion_sync_mensagem',
                'indexes': [
                    models.Index(fields=['external_id'], name='notion_msg_external_idx'),
                    models.Index(fields=['sync_status'], name='notion_msg_status_idx'),
                ],
            },
        ),
    ]
