# Generated by Django 5.2.7 on 2025-10-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0002_enable_pgvector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionDatabaseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único para referência no código",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo da database/página no Notion",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do uso desta configuração",
                    ),
                ),
                (
                    "notion_database_id",
                    models.UUIDField(
                        help_text="ID da database no Notion (formato UUID)"
                    ),
                ),
                (
                    "data_source_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID do data source (API v2025-09-03)",
                        null=True,
                    ),
                ),
                (
                    "notion_page_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID da página principal (opcional, para hierarquias)",
                        null=True,
                    ),
                ),
                (
                    "django_model",
                    models.CharField(
                        help_text="Modelo Django correspondente (app.Model)",
                        max_length=100,
                    ),
                ),
                (
                    "django_app_label",
                    models.CharField(
                        help_text="App Django onde o modelo está definido",
                        max_length=50,
                    ),
                ),
                (
                    "notion_schema",
                    models.JSONField(
                        default=dict,
                        help_text="Schema completo das propriedades do Notion",
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        default=dict,
                        help_text="Mapeamento campo_django → campo_notion",
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Habilita/desabilita sincronização",
                    ),
                ),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("bidirectional", "Bidirecional"),
                            ("django_to_notion", "Django → Notion"),
                            ("notion_to_django", "Notion → Django"),
                        ],
                        default="bidirectional",
                        help_text="Direção da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "sync_priority",
                    models.IntegerField(
                        choices=[
                            (1, "Baixa"),
                            (3, "Média"),
                            (5, "Normal"),
                            (7, "Alta"),
                            (10, "Crítica"),
                        ],
                        default=5,
                        help_text="Prioridade na fila de sincronização",
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True,
                        help_text="Sincroniza automaticamente após alterações",
                    ),
                ),
                (
                    "batch_sync_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Permite sincronização em lote",
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=50,
                        help_text="Tamanho do lote para sincronização em batch",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informações adicionais e configurações customizadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração Notion",
                "verbose_name_plural": "Configurações Notion",
                "db_table": "notion_database_config",
                "ordering": ["sync_priority", "slug"],
                "indexes": [
                    models.Index(
                        fields=["slug"], name="notion_data_slug_9989c6_idx"
                    ),
                    models.Index(
                        fields=["django_model"],
                        name="notion_data_django__5ca377_idx",
                    ),
                    models.Index(
                        fields=["sync_enabled"],
                        name="notion_data_sync_en_2608e2_idx",
                    ),
                    models.Index(
                        fields=["sync_priority"],
                        name="notion_data_sync_pr_515377_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContatoSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da página correspondente no Notion (UUID sem dashes)",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nome_formatado",
                    models.CharField(
                        help_text="Nome já formatado e validado para o Notion",
                        max_length=200,
                    ),
                ),
                (
                    "email_normalizado",
                    models.EmailField(
                        blank=True,
                        help_text="Email validado e normalizado",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "telefone_formatado",
                    models.CharField(
                        blank=True,
                        help_text="Telefone no formato internacional (+55XX999999999)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="É contato principal do cliente?",
                    ),
                ),
                (
                    "tags_formatadas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags formatadas para select/multi-select do Notion",
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades completas formatadas para API Notion",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                            ("disabled", "Desabilitado"),
                        ],
                        default="pending",
                        help_text="Status atual da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do último erro de sincronização",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de tentativas de sincronização",
                    ),
                ),
                (
                    "sync_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informações adicionais sobre a sincronização",
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados adicionais para sincronização",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contato",
                    models.OneToOneField(
                        help_text="Referência ao contato original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="clientes.contato",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para este modelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contato_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato Sync",
                "verbose_name_plural": "Contatos Sync",
                "db_table": "notion_sync_contato",
                "ordering": ["contato__nome_contato"],
                "indexes": [
                    models.Index(
                        fields=["external_id"],
                        name="notion_sync_externa_e7f9da_idx",
                    ),
                    models.Index(
                        fields=["sync_status"],
                        name="notion_sync_sync_st_b57246_idx",
                    ),
                    models.Index(
                        fields=["contato"],
                        name="notion_sync_contato_cad241_idx",
                    ),
                    models.Index(
                        fields=["last_sync_at"],
                        name="notion_sync_last_sy_57cfa5_idx",
                    ),
                    models.Index(
                        fields=["sync_status", "config"],
                        name="notion_sync_sync_st_b9b0b9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClienteSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da página correspondente no Notion",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nome_fantasia_formatado",
                    models.CharField(
                        help_text="Nome fantasia formatado", max_length=200
                    ),
                ),
                (
                    "razao_social_formatada",
                    models.CharField(
                        blank=True,
                        help_text="Razão social formatada",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "cnpj_formatado",
                    models.CharField(
                        blank=True,
                        help_text="CNPJ formatado (apenas dígitos)",
                        max_length=18,
                        null=True,
                    ),
                ),
                (
                    "telefone_formatado",
                    models.CharField(
                        blank=True,
                        help_text="Telefone formatado",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "endereco_completo",
                    models.TextField(
                        blank=True,
                        help_text="Endereço completo formatado",
                        null=True,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                            ("disabled", "Desabilitado"),
                        ],
                        default="pending",
                        help_text="Status atual da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do último erro de sincronização",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de tentativas de sincronização",
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades completas formatadas para API Notion",
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados adicionais para sincronização",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        help_text="Referência ao cliente original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para este modelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente Sync",
                "verbose_name_plural": "Clientes Sync",
                "db_table": "notion_sync_cliente",
                "ordering": ["cliente__nome_fantasia"],
                "indexes": [
                    models.Index(
                        fields=["external_id"],
                        name="notion_sync_externa_8328d8_idx",
                    ),
                    models.Index(
                        fields=["sync_status"],
                        name="notion_sync_sync_st_94ea55_idx",
                    ),
                    models.Index(
                        fields=["cliente"],
                        name="notion_sync_cliente_4ae3d6_idx",
                    ),
                    models.Index(
                        fields=["last_sync_at"],
                        name="notion_sync_last_sy_263c3f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotionObjectMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_model",
                    models.CharField(
                        help_text="Modelo Django (app.Model)", max_length=100
                    ),
                ),
                (
                    "local_id",
                    models.IntegerField(help_text="ID do registro local"),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID da página no Notion",
                        max_length=36,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração utilizada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_mappings",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeamento Notion",
                "verbose_name_plural": "Mapeamentos Notion",
                "db_table": "notion_object_mapping",
                "indexes": [
                    models.Index(
                        fields=["external_id"],
                        name="notion_obje_externa_d7fdb8_idx",
                    ),
                    models.Index(
                        fields=["local_model", "local_id"],
                        name="notion_obje_local_m_051a28_idx",
                    ),
                    models.Index(
                        fields=["config"],
                        name="notion_obje_config__96db87_idx",
                    ),
                ],
                "unique_together": {("local_model", "local_id")},
            },
        ),
    ]
