# Generated by Django 5.2.7 on 2025-10-24 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_atendimento_canal_atendimento_data_primeira_resposta'),
        ('clientes', '0001_initial'),
        ('notion_sync', '0001_initial'),
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='atendentesync',
            new_name='notion_sync_externa_054326_idx',
            old_name='notion_atend_external_idx',
        ),
        migrations.RenameIndex(
            model_name='atendentesync',
            new_name='notion_sync_sync_st_4540ea_idx',
            old_name='notion_atend_status_idx',
        ),
        migrations.RenameIndex(
            model_name='clientesync',
            new_name='notion_sync_externa_8328d8_idx',
            old_name='notion_cliente_external_idx',
        ),
        migrations.RenameIndex(
            model_name='clientesync',
            new_name='notion_sync_sync_st_94ea55_idx',
            old_name='notion_cliente_status_idx',
        ),
        migrations.RenameIndex(
            model_name='clientesync',
            new_name='notion_sync_cliente_4ae3d6_idx',
            old_name='notion_cliente_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='clientesync',
            new_name='notion_sync_last_sy_263c3f_idx',
            old_name='notion_cliente_last_sync_idx',
        ),
        migrations.RenameIndex(
            model_name='contatosync',
            new_name='notion_sync_externa_e7f9da_idx',
            old_name='notion_contato_external_idx',
        ),
        migrations.RenameIndex(
            model_name='contatosync',
            new_name='notion_sync_sync_st_b57246_idx',
            old_name='notion_contato_status_idx',
        ),
        migrations.RenameIndex(
            model_name='contatosync',
            new_name='notion_sync_contato_cad241_idx',
            old_name='notion_contato_contato_idx',
        ),
        migrations.RenameIndex(
            model_name='contatosync',
            new_name='notion_sync_last_sy_57cfa5_idx',
            old_name='notion_contato_last_sync_idx',
        ),
        migrations.RenameIndex(
            model_name='contatosync',
            new_name='notion_sync_sync_st_b9b0b9_idx',
            old_name='notion_contato_status_config_idx',
        ),
        migrations.RenameIndex(
            model_name='departamentosync',
            new_name='notion_sync_externa_8a29e5_idx',
            old_name='notion_depto_external_idx',
        ),
        migrations.RenameIndex(
            model_name='departamentosync',
            new_name='notion_sync_sync_st_59f0aa_idx',
            old_name='notion_depto_status_idx',
        ),
        migrations.RenameIndex(
            model_name='mensagemsync',
            new_name='notion_sync_externa_0e0bb9_idx',
            old_name='notion_msg_external_idx',
        ),
        migrations.RenameIndex(
            model_name='mensagemsync',
            new_name='notion_sync_sync_st_017db6_idx',
            old_name='notion_msg_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notiondatabaseconfig',
            new_name='notion_data_slug_9989c6_idx',
            old_name='notion_db_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='notiondatabaseconfig',
            new_name='notion_data_django__5ca377_idx',
            old_name='notion_db_model_idx',
        ),
        migrations.RenameIndex(
            model_name='notiondatabaseconfig',
            new_name='notion_data_sync_en_2608e2_idx',
            old_name='notion_db_sync_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='notiondatabaseconfig',
            new_name='notion_data_sync_pr_515377_idx',
            old_name='notion_db_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='notionobjectmapping',
            new_name='notion_obje_externa_d7fdb8_idx',
            old_name='notion_map_external_idx',
        ),
        migrations.RenameIndex(
            model_name='notionobjectmapping',
            new_name='notion_obje_local_m_051a28_idx',
            old_name='notion_map_local_idx',
        ),
        migrations.RenameIndex(
            model_name='notionobjectmapping',
            new_name='notion_obje_config__96db87_idx',
            old_name='notion_map_config_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='notion_sync_model_n_43da22_idx',
            old_name='notion_log_model_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='notion_sync_status_b9d9c5_idx',
            old_name='notion_log_status_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='notion_sync_externa_a29817_idx',
            old_name='notion_log_external_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='notion_sync_started_3bb65c_idx',
            old_name='notion_log_started_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='notion_sync_model_n_73f272_idx',
            old_name='notion_log_model_status_idx',
        ),
        migrations.AddField(
            model_name='synclog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação do log'),
        ),
        migrations.AlterField(
            model_name='atendentesync',
            name='atendente',
            field=models.OneToOneField(help_text='Referência ao atendente original', on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='operacional.atendentehumano'),
        ),
        migrations.AlterField(
            model_name='atendentesync',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='atendentesync',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientesync',
            name='cliente',
            field=models.OneToOneField(help_text='Referência ao cliente original', on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='clientesync',
            name='config',
            field=models.ForeignKey(help_text='Configuração Notion para este modelo', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_syncs', to='notion_sync.notiondatabaseconfig'),
        ),
        migrations.AlterField(
            model_name='clientesync',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contatosync',
            name='config',
            field=models.ForeignKey(help_text='Configuração Notion para este modelo', on_delete=django.db.models.deletion.CASCADE, related_name='contato_syncs', to='notion_sync.notiondatabaseconfig'),
        ),
        migrations.AlterField(
            model_name='contatosync',
            name='contato',
            field=models.OneToOneField(help_text='Referência ao contato original', on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='clientes.contato'),
        ),
        migrations.AlterField(
            model_name='contatosync',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departamentosync',
            name='departamento',
            field=models.OneToOneField(help_text='Referência ao departamento original', on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='operacional.departamento'),
        ),
        migrations.AlterField(
            model_name='departamentosync',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='departamentosync',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagemsync',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mensagemsync',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagemsync',
            name='mensagem',
            field=models.OneToOneField(help_text='Referência à mensagem original', on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='atendimentos.mensagem'),
        ),
        migrations.AlterField(
            model_name='notiondatabaseconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notionobjectmapping',
            name='config',
            field=models.ForeignKey(help_text='Configuração utilizada', on_delete=django.db.models.deletion.CASCADE, related_name='object_mappings', to='notion_sync.notiondatabaseconfig'),
        ),
        migrations.AlterField(
            model_name='notionobjectmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='syncconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='config',
            field=models.ForeignKey(help_text='Configuração utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='notion_sync.notiondatabaseconfig'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID do objeto no Notion', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
