# Generated by Django 5.2.5 on 2025-10-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionDatabaseConfig',
            fields=[
                ('id', models.AutoField(help_text='Chave primária do registro', primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="Nome do modelo Django (ex: 'Cliente', 'Contato')", max_length=100, unique=True)),
                ('database_id', models.CharField(help_text='ID do database no Notion', max_length=255, unique=True)),
                ('database_name', models.CharField(help_text='Nome do database no Notion', max_length=200)),
                ('properties_schema', models.JSONField(blank=True, default=dict, help_text='Schema das propriedades/colunas do database')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta configuração está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da configuração')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Database Notion',
                'verbose_name_plural': 'Configurações de Databases Notion',
                'db_table': 'notion_database_config',
                'ordering': ['model_name'],
            },
        ),
    ]
