# Generated by Django 5.2.7 on 2025-10-27 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion_sync", "0001_initial"),
        ("operacional", "0002_enable_pgvector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartamentoSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da página correspondente no Notion",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nome_formatado",
                    models.CharField(
                        help_text="Nome formatado", max_length=100
                    ),
                ),
                (
                    "slug_formatado",
                    models.SlugField(
                        help_text="Slug formatado para URL", max_length=120
                    ),
                ),
                (
                    "descricao_formatada",
                    models.TextField(
                        blank=True, help_text="Descrição formatada", null=True
                    ),
                ),
                (
                    "status_formatado",
                    models.CharField(
                        default="Ativo",
                        help_text="Status formatado (Ativo/Inativo)",
                        max_length=20,
                    ),
                ),
                (
                    "count_atendentes",
                    models.IntegerField(
                        default=0,
                        help_text="Número de atendentes no departamento",
                    ),
                ),
                (
                    "especialidades_formatadas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Especialidades formatadas para multi-select do Notion",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                            ("disabled", "Desabilitado"),
                        ],
                        default="pending",
                        help_text="Status atual da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do último erro de sincronização",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de tentativas de sincronização",
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades completas formatadas para API Notion",
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados adicionais para sincronização",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para este modelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departamento_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
                (
                    "departamento",
                    models.OneToOneField(
                        help_text="Referência ao departamento original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="operacional.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento Sync",
                "verbose_name_plural": "Departamentos Sync",
                "db_table": "notion_sync_departamento",
                "ordering": ["departamento__nome"],
            },
        ),
        migrations.CreateModel(
            name="AtendenteHumanoSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da página correspondente no Notion",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nome_formatado",
                    models.CharField(
                        help_text="Nome formatado", max_length=100
                    ),
                ),
                (
                    "cargo_formatado",
                    models.CharField(
                        help_text="Cargo formatado", max_length=100
                    ),
                ),
                (
                    "departamento_nome",
                    models.CharField(
                        blank=True,
                        help_text="Nome do departamento (cache)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "email_formatado",
                    models.EmailField(
                        blank=True,
                        help_text="Email normalizado",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "telefone_formatado",
                    models.CharField(
                        blank=True,
                        help_text="Telefone formatado",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status_formatado",
                    models.CharField(
                        default="Ativo",
                        help_text="Status formatado (Ativo/Inativo)",
                        max_length=20,
                    ),
                ),
                (
                    "disponibilidade_formatada",
                    models.CharField(
                        default="Disponível",
                        help_text="Disponibilidade formatada",
                        max_length=20,
                    ),
                ),
                (
                    "carga_atual",
                    models.IntegerField(
                        default=0, help_text="Carga atual de atendimentos"
                    ),
                ),
                (
                    "capacidade_maxima",
                    models.IntegerField(
                        default=5,
                        help_text="Capacidade máxima de atendimentos",
                    ),
                ),
                (
                    "especialidades_formatadas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Especialidades formatadas para multi-select do Notion",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                            ("disabled", "Desabilitado"),
                        ],
                        default="pending",
                        help_text="Status atual da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do último erro de sincronização",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de tentativas de sincronização",
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades completas formatadas para API Notion",
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados adicionais para sincronização",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atendente",
                    models.OneToOneField(
                        help_text="Referência ao atendente original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="operacional.atendentehumano",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para este modelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atendente_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
                (
                    "departamento_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do departamento (cache)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendentes_sync",
                        to="notion_sync.departamentosync",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atendente Humano Sync",
                "verbose_name_plural": "Atendentes Humanos Sync",
                "db_table": "notion_sync_atendente_humano",
                "ordering": ["atendente__nome"],
            },
        ),
        migrations.AddIndex(
            model_name="departamentosync",
            index=models.Index(
                fields=["external_id"], name="notion_sync_externa_8a29e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departamentosync",
            index=models.Index(
                fields=["sync_status"], name="notion_sync_sync_st_59f0aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departamentosync",
            index=models.Index(
                fields=["departamento"], name="notion_sync_departa_ce6691_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departamentosync",
            index=models.Index(
                fields=["last_sync_at"], name="notion_sync_last_sy_93118e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departamentosync",
            index=models.Index(
                fields=["sync_status", "config"],
                name="notion_sync_sync_st_f792de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atendentehumanosync",
            index=models.Index(
                fields=["external_id"], name="notion_sync_externa_3a0e94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atendentehumanosync",
            index=models.Index(
                fields=["sync_status"], name="notion_sync_sync_st_59c07a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atendentehumanosync",
            index=models.Index(
                fields=["atendente"], name="notion_sync_atenden_790946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atendentehumanosync",
            index=models.Index(
                fields=["departamento_sync"],
                name="notion_sync_departa_caee88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atendentehumanosync",
            index=models.Index(
                fields=["last_sync_at"], name="notion_sync_last_sy_6cc8dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atendentehumanosync",
            index=models.Index(
                fields=["sync_status", "config"],
                name="notion_sync_sync_st_002c26_idx",
            ),
        ),
    ]
