# Generated by Django 5.2.7 on 2025-10-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_sync', '0002_atendentesync_departamentosync_and_more'),
        ('operacional', '0003_remove_atendentehumano_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendentesync',
            name='atendente',
            field=models.OneToOneField(help_text='Referência ao atendente original', on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='operacional.atendente'),
        ),
        migrations.AddField(
            model_name='atendentesync',
            name='config',
            field=models.ForeignKey(help_text='Configuração Notion para este modelo', on_delete=django.db.models.deletion.CASCADE, related_name='atendente_syncs', to='notion_sync.notiondatabaseconfig'),
        ),
        migrations.AddField(
            model_name='departamentosync',
            name='config',
            field=models.ForeignKey(help_text='Configuração Notion para este modelo', on_delete=django.db.models.deletion.CASCADE, related_name='departamento_syncs', to='notion_sync.notiondatabaseconfig'),
        ),
        migrations.AddField(
            model_name='departamentosync',
            name='departamento',
            field=models.OneToOneField(help_text='Referência ao departamento original', on_delete=django.db.models.deletion.CASCADE, related_name='notion_sync', to='operacional.departamento'),
        ),
        migrations.AddField(
            model_name='atendentesync',
            name='departamento_sync',
            field=models.ForeignKey(blank=True, help_text='Referência ao sync do departamento (cache)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendentes_sync', to='notion_sync.departamentosync'),
        ),
        migrations.AddIndex(
            model_name='departamentosync',
            index=models.Index(fields=['external_id'], name='notion_sync_externa_8a29e5_idx'),
        ),
        migrations.AddIndex(
            model_name='departamentosync',
            index=models.Index(fields=['sync_status'], name='notion_sync_sync_st_59f0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='departamentosync',
            index=models.Index(fields=['departamento'], name='notion_sync_departa_ce6691_idx'),
        ),
        migrations.AddIndex(
            model_name='departamentosync',
            index=models.Index(fields=['last_sync_at'], name='notion_sync_last_sy_93118e_idx'),
        ),
        migrations.AddIndex(
            model_name='departamentosync',
            index=models.Index(fields=['sync_status', 'config'], name='notion_sync_sync_st_f792de_idx'),
        ),
        migrations.AddIndex(
            model_name='atendentesync',
            index=models.Index(fields=['external_id'], name='notion_sync_externa_054326_idx'),
        ),
        migrations.AddIndex(
            model_name='atendentesync',
            index=models.Index(fields=['sync_status'], name='notion_sync_sync_st_4540ea_idx'),
        ),
        migrations.AddIndex(
            model_name='atendentesync',
            index=models.Index(fields=['atendente'], name='notion_sync_atenden_243ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='atendentesync',
            index=models.Index(fields=['departamento_sync'], name='notion_sync_departa_f8868e_idx'),
        ),
        migrations.AddIndex(
            model_name='atendentesync',
            index=models.Index(fields=['last_sync_at'], name='notion_sync_last_sy_e2f1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='atendentesync',
            index=models.Index(fields=['sync_status', 'config'], name='notion_sync_sync_st_df3c93_idx'),
        ),
    ]
