# Generated by Django 5.2.7 on 2025-10-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_sync', '0002_rename_notion_atend_external_idx_notion_sync_externa_054326_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesync',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados adicionais para sincronização'),
        ),
        migrations.AddField(
            model_name='contatosync',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados adicionais para sincronização'),
        ),
    ]
