# Generated by Django 5.2.7 on 2025-10-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atendimentos", "0003_alter_atendimento_atendente_humano"),
        (
            "notion_sync",
            "0003_atendentesync_atendente_atendentesync_config_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AtendimentoSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da página correspondente no Notion",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "protocolo_formatado",
                    models.CharField(
                        help_text="Protocolo formatado para ser o título no Notion",
                        max_length=50,
                    ),
                ),
                (
                    "status_formatado",
                    models.CharField(
                        help_text="Status formatado para o campo Select do Notion",
                        max_length=50,
                    ),
                ),
                (
                    "prioridade_formatada",
                    models.CharField(
                        help_text="Prioridade formatada para o campo Select do Notion",
                        max_length=50,
                    ),
                ),
                (
                    "tags_formatadas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags para o campo Multi-select do Notion",
                    ),
                ),
                (
                    "sla_status",
                    models.CharField(
                        blank=True,
                        help_text="Status calculado do SLA (Ex: OK, Vencido)",
                        max_length=20,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                            ("disabled", "Desabilitado"),
                        ],
                        default="pending",
                        help_text="Status atual da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do último erro de sincronização",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de tentativas de sincronização",
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades completas formatadas para API Notion",
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados adicionais para sincronização",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atendente_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do atendente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos_sync",
                        to="notion_sync.atendentesync",
                    ),
                ),
                (
                    "atendimento",
                    models.OneToOneField(
                        help_text="Referência ao atendimento original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="atendimentos.atendimento",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para este modelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atendimento_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
                (
                    "contato_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do contato",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos_sync",
                        to="notion_sync.contatosync",
                    ),
                ),
                (
                    "departamento_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do departamento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos_sync",
                        to="notion_sync.departamentosync",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atendimento Sync",
                "verbose_name_plural": "Atendimentos Sync",
                "db_table": "notion_sync_atendimento",
                "ordering": ["-atendimento__data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="MensagemSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID do bloco (ou página) correspondente no Notion",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "conteudo_formatado",
                    models.TextField(
                        help_text="Conteúdo formatado e truncado para o Notion"
                    ),
                ),
                (
                    "remetente_formatado",
                    models.CharField(
                        help_text="Nome formatado do remetente", max_length=100
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                            ("disabled", "Desabilitado"),
                        ],
                        default="pending",
                        help_text="Status atual da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do último erro de sincronização",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de tentativas de sincronização",
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades completas formatadas para API Notion",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atendimento_sync",
                    models.ForeignKey(
                        help_text="Referência ao sync do atendimento pai",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_sync",
                        to="notion_sync.atendimentosync",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para este modelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagem_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
                (
                    "mensagem",
                    models.OneToOneField(
                        help_text="Referência à mensagem original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="atendimentos.mensagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem Sync",
                "verbose_name_plural": "Mensagens Sync",
                "db_table": "notion_sync_mensagem",
                "ordering": ["mensagem__timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="atendimentosync",
            index=models.Index(
                fields=["external_id"], name="notion_sync_externa_4e045a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atendimentosync",
            index=models.Index(
                fields=["sync_status"], name="notion_sync_sync_st_92f912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atendimentosync",
            index=models.Index(
                fields=["atendimento"], name="notion_sync_atendim_6e1344_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atendimentosync",
            index=models.Index(
                fields=["contato_sync"], name="notion_sync_contato_9958f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atendimentosync",
            index=models.Index(
                fields=["departamento_sync"],
                name="notion_sync_departa_29e12e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atendimentosync",
            index=models.Index(
                fields=["atendente_sync"],
                name="notion_sync_atenden_3688cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mensagemsync",
            index=models.Index(
                fields=["external_id"], name="notion_sync_externa_0e0bb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensagemsync",
            index=models.Index(
                fields=["sync_status"], name="notion_sync_sync_st_017db6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensagemsync",
            index=models.Index(
                fields=["mensagem"], name="notion_sync_mensage_2ffbe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensagemsync",
            index=models.Index(
                fields=["atendimento_sync"],
                name="notion_sync_atendim_397fcf_idx",
            ),
        ),
    ]
