# Generated by Django 5.2.7 on 2025-11-06 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion_sync", "0004_atendimentosync_mensagemsync_and_more"),
        (
            "operacional",
            "0005_alter_whatsappinstance_options_alter_atendente_ativo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FluxoAtendimentoSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da página correspondente no Notion",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nome_formatado",
                    models.CharField(
                        help_text="Nome do fluxo formatado", max_length=200
                    ),
                ),
                (
                    "descricao_formatada",
                    models.TextField(
                        blank=True, help_text="Descrição formatada", null=True
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                        ],
                        default="pending",
                        help_text="Status da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem de erro de sync",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Número de tentativas de sync"
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades preparadas para Notion",
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        default=dict, help_text="Metadados adicionais"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Atualizado em"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para Fluxo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fluxo_atendimento_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
                (
                    "departamento_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do departamento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fluxos_sync",
                        to="notion_sync.departamentosync",
                    ),
                ),
                (
                    "fluxo",
                    models.OneToOneField(
                        help_text="Referência ao fluxo original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="operacional.fluxoatendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fluxo Atendimento Sync",
                "verbose_name_plural": "Fluxos Atendimento Sync",
                "db_table": "notion_sync_fluxo_atendimento",
                "ordering": ["fluxo__nome"],
            },
        ),
        migrations.CreateModel(
            name="EtapaFluxoSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da página correspondente no Notion",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nome_formatado",
                    models.CharField(
                        help_text="Nome da etapa formatado", max_length=200
                    ),
                ),
                (
                    "descricao_formatada",
                    models.TextField(
                        blank=True, help_text="Descrição formatada", null=True
                    ),
                ),
                (
                    "ordem_formatada",
                    models.IntegerField(default=0, help_text="Ordem da etapa"),
                ),
                (
                    "tipo_formatado",
                    models.CharField(
                        blank=True,
                        help_text="Tipo da etapa",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "permite_atribuicao",
                    models.BooleanField(
                        default=False,
                        help_text="Permite atribuição de atendente",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                        ],
                        default="pending",
                        help_text="Status da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem de erro de sync",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Número de tentativas de sync"
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades preparadas para Notion",
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        default=dict, help_text="Metadados adicionais"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Atualizado em"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para Etapas",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapa_fluxo_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
                (
                    "etapa",
                    models.OneToOneField(
                        help_text="Referência à etapa original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="operacional.etapafluxo",
                    ),
                ),
                (
                    "fluxo_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do fluxo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapas_sync",
                        to="notion_sync.fluxoatendimentosync",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa Fluxo Sync",
                "verbose_name_plural": "Etapas Fluxo Sync",
                "db_table": "notion_sync_etapa_fluxo",
                "ordering": ["ordem_formatada", "etapa__nome"],
            },
        ),
        migrations.CreateModel(
            name="MovimentoFluxoSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da página correspondente no Notion",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("syncing", "Sincronizando"),
                            ("synced", "Sincronizado"),
                            ("error", "Erro"),
                        ],
                        default="pending",
                        help_text="Status da sincronização",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora da última sincronização",
                        null=True,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem de erro de sync",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Número de tentativas de sync"
                    ),
                ),
                (
                    "notion_properties",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades preparadas para Notion",
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        default=dict, help_text="Metadados adicionais"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Atualizado em"
                    ),
                ),
                (
                    "atendente_destino_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do atendente de destino",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_atendente_destino_sync",
                        to="notion_sync.atendentesync",
                    ),
                ),
                (
                    "atendente_origem_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do atendente de origem",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_atendente_origem_sync",
                        to="notion_sync.atendentesync",
                    ),
                ),
                (
                    "atendimento_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync do atendimento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_sync",
                        to="notion_sync.atendimentosync",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuração Notion para Movimentos",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimento_fluxo_syncs",
                        to="notion_sync.notiondatabaseconfig",
                    ),
                ),
                (
                    "etapa_destino_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync da etapa de destino",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_destino_sync",
                        to="notion_sync.etapafluxosync",
                    ),
                ),
                (
                    "etapa_origem_sync",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao sync da etapa de origem",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_origem_sync",
                        to="notion_sync.etapafluxosync",
                    ),
                ),
                (
                    "movimento",
                    models.OneToOneField(
                        help_text="Referência ao movimento original",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_sync",
                        to="operacional.movimentofluxo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento Fluxo Sync",
                "verbose_name_plural": "Movimentos Fluxo Sync",
                "db_table": "notion_sync_movimento_fluxo",
                "ordering": ["movimento__data_movimento"],
            },
        ),
        migrations.AddIndex(
            model_name="fluxoatendimentosync",
            index=models.Index(
                fields=["external_id"], name="notion_sync_externa_8e26d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fluxoatendimentosync",
            index=models.Index(
                fields=["sync_status"], name="notion_sync_sync_st_d39a77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fluxoatendimentosync",
            index=models.Index(
                fields=["fluxo"], name="notion_sync_fluxo_i_30da25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fluxoatendimentosync",
            index=models.Index(
                fields=["last_sync_at"], name="notion_sync_last_sy_7d6d6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fluxoatendimentosync",
            index=models.Index(
                fields=["sync_status", "config"],
                name="notion_sync_sync_st_58a75c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="etapafluxosync",
            index=models.Index(
                fields=["external_id"], name="notion_sync_externa_2b8a8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etapafluxosync",
            index=models.Index(
                fields=["sync_status"], name="notion_sync_sync_st_6fb8b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etapafluxosync",
            index=models.Index(
                fields=["etapa"], name="notion_sync_etapa_i_bd3ab4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etapafluxosync",
            index=models.Index(
                fields=["fluxo_sync"], name="notion_sync_fluxo_s_90bd47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentofluxosync",
            index=models.Index(
                fields=["external_id"], name="notion_sync_externa_df3014_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentofluxosync",
            index=models.Index(
                fields=["sync_status"], name="notion_sync_sync_st_7c0acf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentofluxosync",
            index=models.Index(
                fields=["movimento"], name="notion_sync_movimen_a44b36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentofluxosync",
            index=models.Index(
                fields=["atendimento_sync"],
                name="notion_sync_atendim_d4e286_idx",
            ),
        ),
    ]
