# Generated by Django 5.2.7 on 2026-05-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento_unificado', '0003_gin_index_valor_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Nome curto da etiqueta (ex: 'Urgente', 'VIP').", max_length=50, unique=True)),
                ('cor', models.CharField(default='#a98f71', help_text="Cor hexadecimal usada no chip (ex: '#dc2626').", max_length=7)),
                ('descricao', models.CharField(blank=True, help_text='Descrição exibida no tooltip ao passar o mouse.', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'atu_etiqueta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atendimento_id', models.BigIntegerField(db_index=True, help_text='ID lógico de atendimentos.Atendimento.')),
                ('texto', models.TextField(help_text='Conteúdo livre da nota.')),
                ('criado_por_id', models.BigIntegerField(blank=True, help_text='ID lógico de operacional.Atendente que criou a nota.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'atu_nota',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['atendimento_id', '-criado_em'], name='atu_nota_atend_idx')],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaAtendimento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atendimento_id', models.BigIntegerField(db_index=True, help_text='ID lógico de atendimentos.Atendimento.')),
                ('aplicada_em', models.DateTimeField(auto_now_add=True)),
                ('aplicada_por_id', models.BigIntegerField(blank=True, help_text='ID lógico de operacional.Atendente que aplicou.', null=True)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='atendimento_unificado.etiqueta')),
            ],
            options={
                'verbose_name': 'Etiqueta do Atendimento',
                'verbose_name_plural': 'Etiquetas dos Atendimentos',
                'db_table': 'atu_etiqueta_atendimento',
                'indexes': [models.Index(fields=['atendimento_id'], name='atu_etiq_atend_idx')],
                'unique_together': {('atendimento_id', 'etiqueta')},
            },
        ),
    ]
