# Generated by Django 5.2.7 on 2026-05-23 23:07
# Editada (refatoração modular v6.0): consolida os models de informação em
# `atendimentos`. As tabelas atu_campo/valor/etiqueta/nota são PRESERVADAS
# (apenas o state do Django muda de app — SeparateDatabaseAndState). Apenas
# `atu_leitura_atendimento` é DROPADA (não-lidos passam a usar Mensagem.lido).

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("atendimento_unificado", "0004_etiqueta_nota_etiquetaatendimento"),
    ]

    operations = [
        # LeituraAtendimento: era audit log "quem leu por último"; eliminado.
        # Drop REAL da tabela (não há equivalente em atendimentos).
        migrations.DeleteModel(
            name="LeituraAtendimento",
        ),
        # Demais models: tabelas movidas para `atendimentos` — remover apenas
        # do state do app shell, SEM tocar o banco (database_operations=[]).
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="campopersonalizado",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="valorcampoatendimento",
                    name="campo",
                ),
                migrations.RemoveField(
                    model_name="etiquetaatendimento",
                    name="etiqueta",
                ),
                migrations.AlterUniqueTogether(
                    name="etiquetaatendimento",
                    unique_together=None,
                ),
                migrations.DeleteModel(
                    name="Nota",
                ),
                migrations.AlterUniqueTogether(
                    name="valorcampoatendimento",
                    unique_together=None,
                ),
                migrations.DeleteModel(
                    name="CampoPersonalizado",
                ),
                migrations.DeleteModel(
                    name="ValorCampoAtendimento",
                ),
                migrations.DeleteModel(
                    name="Etiqueta",
                ),
                migrations.DeleteModel(
                    name="EtiquetaAtendimento",
                ),
            ],
        ),
    ]
