# Generated by Django 5.2.7 on 2025-11-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='wa_addressing_mode',
            field=models.CharField(blank=True, help_text="Modo de endereçamento: 'pn' ou 'lid'", max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='wa_jid',
            field=models.CharField(blank=True, help_text='Identificador JID do WhatsApp (ex: 5588@s.whatsapp.net)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='wa_lid',
            field=models.CharField(blank=True, help_text='Identificador alternativo LID (ex: xxxxx@lid)', max_length=100, null=True, unique=True),
        ),
    ]
