# Generated by Django 5.2.7 on 2025-12-06 16:52

import smart_core_assistant_painel.app.ui.clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_contato_wa_addressing_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contatos',
            field=models.ManyToManyField(blank=True, help_text='[CLI-CRM-002] Contatos vinculados ao cliente', related_name='clientes', to='clientes.contato'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, help_text='[CLI-CTT-002] Número de telefone do contato (formato: 5511999999999)', max_length=20, null=True, unique=True, validators=[smart_core_assistant_painel.app.ui.clientes.models.validate_telefone]),
        ),
    ]
